[workspace]
resolver = "2"
members = [
    "rs/xml",
    "rs/global",
    "rs/spreadsheet",
    "rs/presentation",
    "rs/document",
    "rs/ffi",
    "rs-api",
    "ts/document",
    "ts/presentation",
    "ts/spreadsheet",
]
