// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Word_create_return struct {
	_tab flatbuffers.Table
}

func GetRootAsWord_create_return(buf []byte, offset flatbuffers.UOffsetT) *Word_create_return {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Word_create_return{}
	x.Init(buf, n+offset)
	return x
}

func FinishWord_create_returnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWord_create_return(buf []byte, offset flatbuffers.UOffsetT) *Word_create_return {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Word_create_return{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWord_create_returnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Word_create_return) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Word_create_return) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Word_create_return) WordPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Word_create_return) MutateWordPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func Word_create_returnStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func Word_create_returnAddWordPtr(builder *flatbuffers.Builder, wordPtr uint64) {
	builder.PrependUint64Slot(0, wordPtr, 0)
}
func Word_create_returnEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
