// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Word_save_as struct {
	_tab flatbuffers.Table
}

func GetRootAsWord_save_as(buf []byte, offset flatbuffers.UOffsetT) *Word_save_as {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Word_save_as{}
	x.Init(buf, n+offset)
	return x
}

func FinishWord_save_asBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWord_save_as(buf []byte, offset flatbuffers.UOffsetT) *Word_save_as {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Word_save_as{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWord_save_asBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Word_save_as) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Word_save_as) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Word_save_as) WordPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Word_save_as) MutateWordPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Word_save_as) FileName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func Word_save_asStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func Word_save_asAddWordPtr(builder *flatbuffers.Builder, wordPtr uint64) {
	builder.PrependUint64Slot(0, wordPtr, 0)
}
func Word_save_asAddFileName(builder *flatbuffers.Builder, fileName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(fileName), 0)
}
func Word_save_asEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
