[package]
name = "draviavemal-openxml_office"
authors = ["Dravia Vemal"]
description = "Crate to create and manipulate excel,power point and word documents"
license = "MIT"
repository = "https://github.com/DraviaVemal/openxml-office"
documentation = "https://openxml-office.draviavemal.com/"
homepage = "https://openxml-office.draviavemal.com/"
readme = "./README.md"
keywords = ["office", "openxml", "xlsx", "pptx", "docx"]
categories = ["filesystem", "development-tools"]
version = "4.0.0-alpha.6"
edition = "2021"

[dependencies]
uuid = { version = "1.11.0", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
] }
anyhow.workspace = true
chrono.workspace = true
flate2.workspace = true
quick-xml.workspace = true
tempfile.workspace = true
zip.workspace = true
serde = { version = "1.0.215", features = ["derive"] }
phf = { version = "0.11.2", features = ["macros"] }
tokio.workspace = true
rand.workspace = true
dashmap.workspace = true

[dev-dependencies]
criterion = "0.5"
