[package]
name = "draviavemal-openxml_office"
authors = ["Dravia Vemal <contact@draviavemal.com>"]
description = "Crate to create and manipulate excel,power point and word documents"
license = "AGPL-3.0-only"
repository = "https://github.com/DraviaVemal/openxml-office"
documentation = "https://docs.draviavemal.com/openxml-office"
homepage = "https://docs.draviavemal.com/openxml-office"
readme = "./README.md"
keywords = ["office", "openxml", "xlsx", "pptx", "docx"]
categories = ["filesystem", "development-tools"]
version = "4.0.0-alpha.22"
edition = "2021"

[dependencies]
uuid.workspace = true
anyhow.workspace = true
chrono.workspace = true
flate2.workspace = true
quick-xml.workspace = true
zip.workspace = true
serde.workspace = true
phf.workspace = true
tokio.workspace = true
dashmap.workspace = true
blake3.workspace = true
log.workspace = true
draviavemal-xml_rs.workspace = true

[dev-dependencies]
criterion.workspace = true

[features]
document = []
spreadsheet = []
presentation = ["spreadsheet"]
all = ["document", "spreadsheet", "presentation"]
default = ["all"]
