// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type word_settings struct {
	_tab flatbuffers.Table
}

func GetRootAsword_settings(buf []byte, offset flatbuffers.UOffsetT) *word_settings {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &word_settings{}
	x.Init(buf, n+offset)
	return x
}

func Finishword_settingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsword_settings(buf []byte, offset flatbuffers.UOffsetT) *word_settings {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &word_settings{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedword_settingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *word_settings) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *word_settings) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *word_settings) IsEditable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *word_settings) MutateIsEditable(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func word_settingsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func word_settingsAddIsEditable(builder *flatbuffers.Builder, isEditable bool) {
	builder.PrependBoolSlot(0, isEditable, false)
}
func word_settingsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
