// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import "strconv"

type Border_style_values int32

const (
	Border_style_valuesnone                Border_style_values = 0
	Border_style_valuesthin                Border_style_values = 1
	Border_style_valuesthick               Border_style_values = 2
	Border_style_valuesdotted              Border_style_values = 3
	Border_style_valuesdouble              Border_style_values = 4
	Border_style_valuesdashed              Border_style_values = 5
	Border_style_valuesdash_dot            Border_style_values = 6
	Border_style_valuesdash_dot_dot        Border_style_values = 7
	Border_style_valuesmedium              Border_style_values = 8
	Border_style_valuesmedium_dashed       Border_style_values = 9
	Border_style_valuesmedium_dash_dot     Border_style_values = 10
	Border_style_valuesmedium_dash_dot_dot Border_style_values = 11
	Border_style_valuesslant_dash_dot      Border_style_values = 12
)

var EnumNamesBorder_style_values = map[Border_style_values]string{
	Border_style_valuesnone:                "none",
	Border_style_valuesthin:                "thin",
	Border_style_valuesthick:               "thick",
	Border_style_valuesdotted:              "dotted",
	Border_style_valuesdouble:              "double",
	Border_style_valuesdashed:              "dashed",
	Border_style_valuesdash_dot:            "dash_dot",
	Border_style_valuesdash_dot_dot:        "dash_dot_dot",
	Border_style_valuesmedium:              "medium",
	Border_style_valuesmedium_dashed:       "medium_dashed",
	Border_style_valuesmedium_dash_dot:     "medium_dash_dot",
	Border_style_valuesmedium_dash_dot_dot: "medium_dash_dot_dot",
	Border_style_valuesslant_dash_dot:      "slant_dash_dot",
}

var EnumValuesBorder_style_values = map[string]Border_style_values{
	"none":                Border_style_valuesnone,
	"thin":                Border_style_valuesthin,
	"thick":               Border_style_valuesthick,
	"dotted":              Border_style_valuesdotted,
	"double":              Border_style_valuesdouble,
	"dashed":              Border_style_valuesdashed,
	"dash_dot":            Border_style_valuesdash_dot,
	"dash_dot_dot":        Border_style_valuesdash_dot_dot,
	"medium":              Border_style_valuesmedium,
	"medium_dashed":       Border_style_valuesmedium_dashed,
	"medium_dash_dot":     Border_style_valuesmedium_dash_dot,
	"medium_dash_dot_dot": Border_style_valuesmedium_dash_dot_dot,
	"slant_dash_dot":      Border_style_valuesslant_dash_dot,
}

func (v Border_style_values) String() string {
	if s, ok := EnumNamesBorder_style_values[v]; ok {
		return s
	}
	return "Border_style_values(" + strconv.FormatInt(int64(v), 10) + ")"
}
