// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import "strconv"

type border_style_values int32

const (
	border_style_valuesnone                border_style_values = 0
	border_style_valuesthin                border_style_values = 1
	border_style_valuesthick               border_style_values = 2
	border_style_valuesdotted              border_style_values = 3
	border_style_valuesdouble              border_style_values = 4
	border_style_valuesdashed              border_style_values = 5
	border_style_valuesdash_dot            border_style_values = 6
	border_style_valuesdash_dot_dot        border_style_values = 7
	border_style_valuesmedium              border_style_values = 8
	border_style_valuesmedium_dashed       border_style_values = 9
	border_style_valuesmedium_dash_dot     border_style_values = 10
	border_style_valuesmedium_dash_dot_dot border_style_values = 11
	border_style_valuesslant_dash_dot      border_style_values = 12
)

var EnumNamesborder_style_values = map[border_style_values]string{
	border_style_valuesnone:                "none",
	border_style_valuesthin:                "thin",
	border_style_valuesthick:               "thick",
	border_style_valuesdotted:              "dotted",
	border_style_valuesdouble:              "double",
	border_style_valuesdashed:              "dashed",
	border_style_valuesdash_dot:            "dash_dot",
	border_style_valuesdash_dot_dot:        "dash_dot_dot",
	border_style_valuesmedium:              "medium",
	border_style_valuesmedium_dashed:       "medium_dashed",
	border_style_valuesmedium_dash_dot:     "medium_dash_dot",
	border_style_valuesmedium_dash_dot_dot: "medium_dash_dot_dot",
	border_style_valuesslant_dash_dot:      "slant_dash_dot",
}

var EnumValuesborder_style_values = map[string]border_style_values{
	"none":                border_style_valuesnone,
	"thin":                border_style_valuesthin,
	"thick":               border_style_valuesthick,
	"dotted":              border_style_valuesdotted,
	"double":              border_style_valuesdouble,
	"dashed":              border_style_valuesdashed,
	"dash_dot":            border_style_valuesdash_dot,
	"dash_dot_dot":        border_style_valuesdash_dot_dot,
	"medium":              border_style_valuesmedium,
	"medium_dashed":       border_style_valuesmedium_dashed,
	"medium_dash_dot":     border_style_valuesmedium_dash_dot,
	"medium_dash_dot_dot": border_style_valuesmedium_dash_dot_dot,
	"slant_dash_dot":      border_style_valuesslant_dash_dot,
}

func (v border_style_values) String() string {
	if s, ok := EnumNamesborder_style_values[v]; ok {
		return s
	}
	return "border_style_values(" + strconv.FormatInt(int64(v), 10) + ")"
}
