// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import "strconv"

type Color_setting_type_values int32

const (
	Color_setting_type_valuesindexed Color_setting_type_values = 0
	Color_setting_type_valuestheme   Color_setting_type_values = 1
	Color_setting_type_valuesrgb     Color_setting_type_values = 2
)

var EnumNamesColor_setting_type_values = map[Color_setting_type_values]string{
	Color_setting_type_valuesindexed: "indexed",
	Color_setting_type_valuestheme:   "theme",
	Color_setting_type_valuesrgb:     "rgb",
}

var EnumValuesColor_setting_type_values = map[string]Color_setting_type_values{
	"indexed": Color_setting_type_valuesindexed,
	"theme":   Color_setting_type_valuestheme,
	"rgb":     Color_setting_type_valuesrgb,
}

func (v Color_setting_type_values) String() string {
	if s, ok := EnumNamesColor_setting_type_values[v]; ok {
		return s
	}
	return "Color_setting_type_values(" + strconv.FormatInt(int64(v), 10) + ")"
}
