// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import "strconv"

type color_setting_type_values int32

const (
	color_setting_type_valuesindexed color_setting_type_values = 0
	color_setting_type_valuestheme   color_setting_type_values = 1
	color_setting_type_valuesrgb     color_setting_type_values = 2
)

var EnumNamescolor_setting_type_values = map[color_setting_type_values]string{
	color_setting_type_valuesindexed: "indexed",
	color_setting_type_valuestheme:   "theme",
	color_setting_type_valuesrgb:     "rgb",
}

var EnumValuescolor_setting_type_values = map[string]color_setting_type_values{
	"indexed": color_setting_type_valuesindexed,
	"theme":   color_setting_type_valuestheme,
	"rgb":     color_setting_type_valuesrgb,
}

func (v color_setting_type_values) String() string {
	if s, ok := EnumNamescolor_setting_type_values[v]; ok {
		return s
	}
	return "color_setting_type_values(" + strconv.FormatInt(int64(v), 10) + ")"
}
