// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Excel_hide_horizontal_scroll struct {
	_tab flatbuffers.Table
}

func GetRootAsExcel_hide_horizontal_scroll(buf []byte, offset flatbuffers.UOffsetT) *Excel_hide_horizontal_scroll {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Excel_hide_horizontal_scroll{}
	x.Init(buf, n+offset)
	return x
}

func FinishExcel_hide_horizontal_scrollBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsExcel_hide_horizontal_scroll(buf []byte, offset flatbuffers.UOffsetT) *Excel_hide_horizontal_scroll {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Excel_hide_horizontal_scroll{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedExcel_hide_horizontal_scrollBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Excel_hide_horizontal_scroll) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Excel_hide_horizontal_scroll) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Excel_hide_horizontal_scroll) ExcelPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Excel_hide_horizontal_scroll) MutateExcelPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Excel_hide_horizontal_scroll) HideHorizontalScroll() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Excel_hide_horizontal_scroll) MutateHideHorizontalScroll(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func Excel_hide_horizontal_scrollStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func Excel_hide_horizontal_scrollAddExcelPtr(builder *flatbuffers.Builder, excelPtr uint64) {
	builder.PrependUint64Slot(0, excelPtr, 0)
}
func Excel_hide_horizontal_scrollAddHideHorizontalScroll(builder *flatbuffers.Builder, hideHorizontalScroll bool) {
	builder.PrependBoolSlot(1, hideHorizontalScroll, false)
}
func Excel_hide_horizontal_scrollEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
