// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type excel_create_return struct {
	_tab flatbuffers.Table
}

func GetRootAsexcel_create_return(buf []byte, offset flatbuffers.UOffsetT) *excel_create_return {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &excel_create_return{}
	x.Init(buf, n+offset)
	return x
}

func Finishexcel_create_returnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsexcel_create_return(buf []byte, offset flatbuffers.UOffsetT) *excel_create_return {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &excel_create_return{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedexcel_create_returnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *excel_create_return) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *excel_create_return) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *excel_create_return) ExcelPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *excel_create_return) MutateExcelPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func excel_create_returnStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func excel_create_returnAddExcelPtr(builder *flatbuffers.Builder, excelPtr uint64) {
	builder.PrependUint64Slot(0, excelPtr, 0)
}
func excel_create_returnEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
