// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Excel_minimize_workbook struct {
	_tab flatbuffers.Table
}

func GetRootAsExcel_minimize_workbook(buf []byte, offset flatbuffers.UOffsetT) *Excel_minimize_workbook {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Excel_minimize_workbook{}
	x.Init(buf, n+offset)
	return x
}

func FinishExcel_minimize_workbookBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsExcel_minimize_workbook(buf []byte, offset flatbuffers.UOffsetT) *Excel_minimize_workbook {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Excel_minimize_workbook{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedExcel_minimize_workbookBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Excel_minimize_workbook) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Excel_minimize_workbook) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Excel_minimize_workbook) ExcelPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Excel_minimize_workbook) MutateExcelPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Excel_minimize_workbook) IsMinimized() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Excel_minimize_workbook) MutateIsMinimized(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func Excel_minimize_workbookStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func Excel_minimize_workbookAddExcelPtr(builder *flatbuffers.Builder, excelPtr uint64) {
	builder.PrependUint64Slot(0, excelPtr, 0)
}
func Excel_minimize_workbookAddIsMinimized(builder *flatbuffers.Builder, isMinimized bool) {
	builder.PrependBoolSlot(1, isMinimized, false)
}
func Excel_minimize_workbookEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
