// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Excel_get_sheet_return struct {
	_tab flatbuffers.Table
}

func GetRootAsExcel_get_sheet_return(buf []byte, offset flatbuffers.UOffsetT) *Excel_get_sheet_return {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Excel_get_sheet_return{}
	x.Init(buf, n+offset)
	return x
}

func FinishExcel_get_sheet_returnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsExcel_get_sheet_return(buf []byte, offset flatbuffers.UOffsetT) *Excel_get_sheet_return {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Excel_get_sheet_return{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedExcel_get_sheet_returnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Excel_get_sheet_return) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Excel_get_sheet_return) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Excel_get_sheet_return) WorksheetPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Excel_get_sheet_return) MutateWorksheetPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func Excel_get_sheet_returnStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func Excel_get_sheet_returnAddWorksheetPtr(builder *flatbuffers.Builder, worksheetPtr uint64) {
	builder.PrependUint64Slot(0, worksheetPtr, 0)
}
func Excel_get_sheet_returnEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
