// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type excel_hide_vertical_scroll struct {
	_tab flatbuffers.Table
}

func GetRootAsexcel_hide_vertical_scroll(buf []byte, offset flatbuffers.UOffsetT) *excel_hide_vertical_scroll {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &excel_hide_vertical_scroll{}
	x.Init(buf, n+offset)
	return x
}

func Finishexcel_hide_vertical_scrollBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsexcel_hide_vertical_scroll(buf []byte, offset flatbuffers.UOffsetT) *excel_hide_vertical_scroll {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &excel_hide_vertical_scroll{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedexcel_hide_vertical_scrollBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *excel_hide_vertical_scroll) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *excel_hide_vertical_scroll) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *excel_hide_vertical_scroll) ExcelPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *excel_hide_vertical_scroll) MutateExcelPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *excel_hide_vertical_scroll) HideVerticalScroll() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *excel_hide_vertical_scroll) MutateHideVerticalScroll(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func excel_hide_vertical_scrollStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func excel_hide_vertical_scrollAddExcelPtr(builder *flatbuffers.Builder, excelPtr uint64) {
	builder.PrependUint64Slot(0, excelPtr, 0)
}
func excel_hide_vertical_scrollAddHideVerticalScroll(builder *flatbuffers.Builder, hideVerticalScroll bool) {
	builder.PrependBoolSlot(1, hideVerticalScroll, false)
}
func excel_hide_vertical_scrollEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
