// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Excel_get_style_id struct {
	_tab flatbuffers.Table
}

func GetRootAsExcel_get_style_id(buf []byte, offset flatbuffers.UOffsetT) *Excel_get_style_id {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Excel_get_style_id{}
	x.Init(buf, n+offset)
	return x
}

func FinishExcel_get_style_idBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsExcel_get_style_id(buf []byte, offset flatbuffers.UOffsetT) *Excel_get_style_id {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Excel_get_style_id{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedExcel_get_style_idBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Excel_get_style_id) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Excel_get_style_id) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Excel_get_style_id) ExcelPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Excel_get_style_id) MutateExcelPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Excel_get_style_id) StyleSetting(obj *Excel_style_setting) *Excel_style_setting {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Excel_style_setting)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func Excel_get_style_idStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func Excel_get_style_idAddExcelPtr(builder *flatbuffers.Builder, excelPtr uint64) {
	builder.PrependUint64Slot(0, excelPtr, 0)
}
func Excel_get_style_idAddStyleSetting(builder *flatbuffers.Builder, styleSetting flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(styleSetting), 0)
}
func Excel_get_style_idEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
