// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Excel_settings struct {
	_tab flatbuffers.Table
}

func GetRootAsExcel_settings(buf []byte, offset flatbuffers.UOffsetT) *Excel_settings {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Excel_settings{}
	x.Init(buf, n+offset)
	return x
}

func FinishExcel_settingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsExcel_settings(buf []byte, offset flatbuffers.UOffsetT) *Excel_settings {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Excel_settings{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedExcel_settingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Excel_settings) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Excel_settings) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Excel_settings) IsEditable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Excel_settings) MutateIsEditable(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func Excel_settingsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func Excel_settingsAddIsEditable(builder *flatbuffers.Builder, isEditable bool) {
	builder.PrependBoolSlot(0, isEditable, false)
}
func Excel_settingsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
