// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type excel_border_settings struct {
	_tab flatbuffers.Table
}

func GetRootAsexcel_border_settings(buf []byte, offset flatbuffers.UOffsetT) *excel_border_settings {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &excel_border_settings{}
	x.Init(buf, n+offset)
	return x
}

func Finishexcel_border_settingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsexcel_border_settings(buf []byte, offset flatbuffers.UOffsetT) *excel_border_settings {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &excel_border_settings{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedexcel_border_settingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *excel_border_settings) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *excel_border_settings) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *excel_border_settings) BorderColor(obj *excel_color_setting) *excel_color_setting {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(excel_color_setting)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *excel_border_settings) Style() border_style_values {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return border_style_values(rcv._tab.GetInt32(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *excel_border_settings) MutateStyle(n border_style_values) bool {
	return rcv._tab.MutateInt32Slot(6, int32(n))
}

func excel_border_settingsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func excel_border_settingsAddBorderColor(builder *flatbuffers.Builder, borderColor flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(borderColor), 0)
}
func excel_border_settingsAddStyle(builder *flatbuffers.Builder, style border_style_values) {
	builder.PrependInt32Slot(1, int32(style), 0)
}
func excel_border_settingsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
