// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Excel_list_sheet struct {
	_tab flatbuffers.Table
}

func GetRootAsExcel_list_sheet(buf []byte, offset flatbuffers.UOffsetT) *Excel_list_sheet {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Excel_list_sheet{}
	x.Init(buf, n+offset)
	return x
}

func FinishExcel_list_sheetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsExcel_list_sheet(buf []byte, offset flatbuffers.UOffsetT) *Excel_list_sheet {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Excel_list_sheet{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedExcel_list_sheetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Excel_list_sheet) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Excel_list_sheet) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Excel_list_sheet) ExcelPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Excel_list_sheet) MutateExcelPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func Excel_list_sheetStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func Excel_list_sheetAddExcelPtr(builder *flatbuffers.Builder, excelPtr uint64) {
	builder.PrependUint64Slot(0, excelPtr, 0)
}
func Excel_list_sheetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
