// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type excel_set_visibility struct {
	_tab flatbuffers.Table
}

func GetRootAsexcel_set_visibility(buf []byte, offset flatbuffers.UOffsetT) *excel_set_visibility {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &excel_set_visibility{}
	x.Init(buf, n+offset)
	return x
}

func Finishexcel_set_visibilityBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsexcel_set_visibility(buf []byte, offset flatbuffers.UOffsetT) *excel_set_visibility {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &excel_set_visibility{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedexcel_set_visibilityBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *excel_set_visibility) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *excel_set_visibility) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *excel_set_visibility) ExcelPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *excel_set_visibility) MutateExcelPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *excel_set_visibility) IsVisible() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *excel_set_visibility) MutateIsVisible(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func excel_set_visibilityStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func excel_set_visibilityAddExcelPtr(builder *flatbuffers.Builder, excelPtr uint64) {
	builder.PrependUint64Slot(0, excelPtr, 0)
}
func excel_set_visibilityAddIsVisible(builder *flatbuffers.Builder, isVisible bool) {
	builder.PrependBoolSlot(1, isVisible, false)
}
func excel_set_visibilityEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
