// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Excel_rename_sheet struct {
	_tab flatbuffers.Table
}

func GetRootAsExcel_rename_sheet(buf []byte, offset flatbuffers.UOffsetT) *Excel_rename_sheet {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Excel_rename_sheet{}
	x.Init(buf, n+offset)
	return x
}

func FinishExcel_rename_sheetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsExcel_rename_sheet(buf []byte, offset flatbuffers.UOffsetT) *Excel_rename_sheet {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Excel_rename_sheet{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedExcel_rename_sheetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Excel_rename_sheet) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Excel_rename_sheet) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Excel_rename_sheet) ExcelPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Excel_rename_sheet) MutateExcelPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Excel_rename_sheet) OldSheetName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Excel_rename_sheet) NewSheetName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func Excel_rename_sheetStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func Excel_rename_sheetAddExcelPtr(builder *flatbuffers.Builder, excelPtr uint64) {
	builder.PrependUint64Slot(0, excelPtr, 0)
}
func Excel_rename_sheetAddOldSheetName(builder *flatbuffers.Builder, oldSheetName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(oldSheetName), 0)
}
func Excel_rename_sheetAddNewSheetName(builder *flatbuffers.Builder, newSheetName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(newSheetName), 0)
}
func Excel_rename_sheetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
