// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type excel_style_setting struct {
	_tab flatbuffers.Table
}

func GetRootAsexcel_style_setting(buf []byte, offset flatbuffers.UOffsetT) *excel_style_setting {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &excel_style_setting{}
	x.Init(buf, n+offset)
	return x
}

func Finishexcel_style_settingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsexcel_style_setting(buf []byte, offset flatbuffers.UOffsetT) *excel_style_setting {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &excel_style_setting{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedexcel_style_settingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *excel_style_setting) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *excel_style_setting) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *excel_style_setting) NumberFormat() number_format_values {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return number_format_values(rcv._tab.GetInt32(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *excel_style_setting) MutateNumberFormat(n number_format_values) bool {
	return rcv._tab.MutateInt32Slot(4, int32(n))
}

func (rcv *excel_style_setting) CustomNumberFormat() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *excel_style_setting) BorderLeft(obj *excel_border_settings) *excel_border_settings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(excel_border_settings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *excel_style_setting) BorderTop(obj *excel_border_settings) *excel_border_settings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(excel_border_settings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *excel_style_setting) BorderRight(obj *excel_border_settings) *excel_border_settings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(excel_border_settings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *excel_style_setting) BorderBottom(obj *excel_border_settings) *excel_border_settings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(excel_border_settings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *excel_style_setting) BorderDiagonal(obj *excel_border_settings) *excel_border_settings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(excel_border_settings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *excel_style_setting) FontFamily() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *excel_style_setting) FontSize() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *excel_style_setting) MutateFontSize(n byte) bool {
	return rcv._tab.MutateByteSlot(20, n)
}

func (rcv *excel_style_setting) TextColor(obj *excel_color_setting) *excel_color_setting {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(excel_color_setting)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *excel_style_setting) IsBold() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *excel_style_setting) MutateIsBold(n bool) bool {
	return rcv._tab.MutateBoolSlot(24, n)
}

func (rcv *excel_style_setting) IsItalic() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *excel_style_setting) MutateIsItalic(n bool) bool {
	return rcv._tab.MutateBoolSlot(26, n)
}

func (rcv *excel_style_setting) IsUnderline() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *excel_style_setting) MutateIsUnderline(n bool) bool {
	return rcv._tab.MutateBoolSlot(28, n)
}

func (rcv *excel_style_setting) IsDoubleUnderline() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *excel_style_setting) MutateIsDoubleUnderline(n bool) bool {
	return rcv._tab.MutateBoolSlot(30, n)
}

func (rcv *excel_style_setting) IsWrapText() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *excel_style_setting) MutateIsWrapText(n bool) bool {
	return rcv._tab.MutateBoolSlot(32, n)
}

func (rcv *excel_style_setting) BackgroundColor() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *excel_style_setting) ForegroundColor() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *excel_style_setting) HorizontalAlignment() horizontal_alignment_values {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		return horizontal_alignment_values(rcv._tab.GetInt32(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *excel_style_setting) MutateHorizontalAlignment(n horizontal_alignment_values) bool {
	return rcv._tab.MutateInt32Slot(38, int32(n))
}

func (rcv *excel_style_setting) VerticalAlignment() vertical_alignment_values {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(40))
	if o != 0 {
		return vertical_alignment_values(rcv._tab.GetInt32(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *excel_style_setting) MutateVerticalAlignment(n vertical_alignment_values) bool {
	return rcv._tab.MutateInt32Slot(40, int32(n))
}

func excel_style_settingStart(builder *flatbuffers.Builder) {
	builder.StartObject(19)
}
func excel_style_settingAddNumberFormat(builder *flatbuffers.Builder, numberFormat number_format_values) {
	builder.PrependInt32Slot(0, int32(numberFormat), 0)
}
func excel_style_settingAddCustomNumberFormat(builder *flatbuffers.Builder, customNumberFormat flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(customNumberFormat), 0)
}
func excel_style_settingAddBorderLeft(builder *flatbuffers.Builder, borderLeft flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(borderLeft), 0)
}
func excel_style_settingAddBorderTop(builder *flatbuffers.Builder, borderTop flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(borderTop), 0)
}
func excel_style_settingAddBorderRight(builder *flatbuffers.Builder, borderRight flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(borderRight), 0)
}
func excel_style_settingAddBorderBottom(builder *flatbuffers.Builder, borderBottom flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(borderBottom), 0)
}
func excel_style_settingAddBorderDiagonal(builder *flatbuffers.Builder, borderDiagonal flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(borderDiagonal), 0)
}
func excel_style_settingAddFontFamily(builder *flatbuffers.Builder, fontFamily flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(fontFamily), 0)
}
func excel_style_settingAddFontSize(builder *flatbuffers.Builder, fontSize byte) {
	builder.PrependByteSlot(8, fontSize, 0)
}
func excel_style_settingAddTextColor(builder *flatbuffers.Builder, textColor flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(textColor), 0)
}
func excel_style_settingAddIsBold(builder *flatbuffers.Builder, isBold bool) {
	builder.PrependBoolSlot(10, isBold, false)
}
func excel_style_settingAddIsItalic(builder *flatbuffers.Builder, isItalic bool) {
	builder.PrependBoolSlot(11, isItalic, false)
}
func excel_style_settingAddIsUnderline(builder *flatbuffers.Builder, isUnderline bool) {
	builder.PrependBoolSlot(12, isUnderline, false)
}
func excel_style_settingAddIsDoubleUnderline(builder *flatbuffers.Builder, isDoubleUnderline bool) {
	builder.PrependBoolSlot(13, isDoubleUnderline, false)
}
func excel_style_settingAddIsWrapText(builder *flatbuffers.Builder, isWrapText bool) {
	builder.PrependBoolSlot(14, isWrapText, false)
}
func excel_style_settingAddBackgroundColor(builder *flatbuffers.Builder, backgroundColor flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(15, flatbuffers.UOffsetT(backgroundColor), 0)
}
func excel_style_settingAddForegroundColor(builder *flatbuffers.Builder, foregroundColor flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(16, flatbuffers.UOffsetT(foregroundColor), 0)
}
func excel_style_settingAddHorizontalAlignment(builder *flatbuffers.Builder, horizontalAlignment horizontal_alignment_values) {
	builder.PrependInt32Slot(17, int32(horizontalAlignment), 0)
}
func excel_style_settingAddVerticalAlignment(builder *flatbuffers.Builder, verticalAlignment vertical_alignment_values) {
	builder.PrependInt32Slot(18, int32(verticalAlignment), 0)
}
func excel_style_settingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
