// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Excel_save_as_return struct {
	_tab flatbuffers.Table
}

func GetRootAsExcel_save_as_return(buf []byte, offset flatbuffers.UOffsetT) *Excel_save_as_return {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Excel_save_as_return{}
	x.Init(buf, n+offset)
	return x
}

func FinishExcel_save_as_returnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsExcel_save_as_return(buf []byte, offset flatbuffers.UOffsetT) *Excel_save_as_return {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Excel_save_as_return{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedExcel_save_as_returnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Excel_save_as_return) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Excel_save_as_return) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Excel_save_as_return) FullPath() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func Excel_save_as_returnStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func Excel_save_as_returnAddFullPath(builder *flatbuffers.Builder, fullPath flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(fullPath), 0)
}
func Excel_save_as_returnEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
