// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Excel_list_sheet_return struct {
	_tab flatbuffers.Table
}

func GetRootAsExcel_list_sheet_return(buf []byte, offset flatbuffers.UOffsetT) *Excel_list_sheet_return {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Excel_list_sheet_return{}
	x.Init(buf, n+offset)
	return x
}

func FinishExcel_list_sheet_returnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsExcel_list_sheet_return(buf []byte, offset flatbuffers.UOffsetT) *Excel_list_sheet_return {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Excel_list_sheet_return{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedExcel_list_sheet_returnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Excel_list_sheet_return) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Excel_list_sheet_return) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Excel_list_sheet_return) SheetNames(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *Excel_list_sheet_return) SheetNamesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func Excel_list_sheet_returnStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func Excel_list_sheet_returnAddSheetNames(builder *flatbuffers.Builder, sheetNames flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(sheetNames), 0)
}
func Excel_list_sheet_returnStartSheetNamesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func Excel_list_sheet_returnEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
