// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type excel_hide_sheet struct {
	_tab flatbuffers.Table
}

func GetRootAsexcel_hide_sheet(buf []byte, offset flatbuffers.UOffsetT) *excel_hide_sheet {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &excel_hide_sheet{}
	x.Init(buf, n+offset)
	return x
}

func Finishexcel_hide_sheetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsexcel_hide_sheet(buf []byte, offset flatbuffers.UOffsetT) *excel_hide_sheet {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &excel_hide_sheet{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedexcel_hide_sheetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *excel_hide_sheet) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *excel_hide_sheet) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *excel_hide_sheet) ExcelPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *excel_hide_sheet) MutateExcelPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *excel_hide_sheet) SheetName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func excel_hide_sheetStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func excel_hide_sheetAddExcelPtr(builder *flatbuffers.Builder, excelPtr uint64) {
	builder.PrependUint64Slot(0, excelPtr, 0)
}
func excel_hide_sheetAddSheetName(builder *flatbuffers.Builder, sheetName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(sheetName), 0)
}
func excel_hide_sheetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
