// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type excel_color_setting struct {
	_tab flatbuffers.Table
}

func GetRootAsexcel_color_setting(buf []byte, offset flatbuffers.UOffsetT) *excel_color_setting {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &excel_color_setting{}
	x.Init(buf, n+offset)
	return x
}

func Finishexcel_color_settingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsexcel_color_setting(buf []byte, offset flatbuffers.UOffsetT) *excel_color_setting {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &excel_color_setting{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedexcel_color_settingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *excel_color_setting) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *excel_color_setting) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *excel_color_setting) ColorSettingType() color_setting_type_values {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return color_setting_type_values(rcv._tab.GetInt32(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *excel_color_setting) MutateColorSettingType(n color_setting_type_values) bool {
	return rcv._tab.MutateInt32Slot(4, int32(n))
}

func (rcv *excel_color_setting) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func excel_color_settingStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func excel_color_settingAddColorSettingType(builder *flatbuffers.Builder, colorSettingType color_setting_type_values) {
	builder.PrependInt32Slot(0, int32(colorSettingType), 0)
}
func excel_color_settingAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func excel_color_settingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
