// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import "strconv"

type horizontal_alignment_values int32

const (
	horizontal_alignment_valuesnone    horizontal_alignment_values = 0
	horizontal_alignment_valuesleft    horizontal_alignment_values = 1
	horizontal_alignment_valuescenter  horizontal_alignment_values = 2
	horizontal_alignment_valuesright   horizontal_alignment_values = 3
	horizontal_alignment_valuesjustify horizontal_alignment_values = 4
)

var EnumNameshorizontal_alignment_values = map[horizontal_alignment_values]string{
	horizontal_alignment_valuesnone:    "none",
	horizontal_alignment_valuesleft:    "left",
	horizontal_alignment_valuescenter:  "center",
	horizontal_alignment_valuesright:   "right",
	horizontal_alignment_valuesjustify: "justify",
}

var EnumValueshorizontal_alignment_values = map[string]horizontal_alignment_values{
	"none":    horizontal_alignment_valuesnone,
	"left":    horizontal_alignment_valuesleft,
	"center":  horizontal_alignment_valuescenter,
	"right":   horizontal_alignment_valuesright,
	"justify": horizontal_alignment_valuesjustify,
}

func (v horizontal_alignment_values) String() string {
	if s, ok := EnumNameshorizontal_alignment_values[v]; ok {
		return s
	}
	return "horizontal_alignment_values(" + strconv.FormatInt(int64(v), 10) + ")"
}
