// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import "strconv"

type Horizontal_alignment_values int32

const (
	Horizontal_alignment_valuesnone    Horizontal_alignment_values = 0
	Horizontal_alignment_valuesleft    Horizontal_alignment_values = 1
	Horizontal_alignment_valuescenter  Horizontal_alignment_values = 2
	Horizontal_alignment_valuesright   Horizontal_alignment_values = 3
	Horizontal_alignment_valuesjustify Horizontal_alignment_values = 4
)

var EnumNamesHorizontal_alignment_values = map[Horizontal_alignment_values]string{
	Horizontal_alignment_valuesnone:    "none",
	Horizontal_alignment_valuesleft:    "left",
	Horizontal_alignment_valuescenter:  "center",
	Horizontal_alignment_valuesright:   "right",
	Horizontal_alignment_valuesjustify: "justify",
}

var EnumValuesHorizontal_alignment_values = map[string]Horizontal_alignment_values{
	"none":    Horizontal_alignment_valuesnone,
	"left":    Horizontal_alignment_valuesleft,
	"center":  Horizontal_alignment_valuescenter,
	"right":   Horizontal_alignment_valuesright,
	"justify": Horizontal_alignment_valuesjustify,
}

func (v Horizontal_alignment_values) String() string {
	if s, ok := EnumNamesHorizontal_alignment_values[v]; ok {
		return s
	}
	return "Horizontal_alignment_values(" + strconv.FormatInt(int64(v), 10) + ")"
}
