// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import "strconv"

type number_format_values int32

const (
	number_format_valuesgeneral                                         number_format_values = 0
	number_format_valuesinteger                                         number_format_values = 1
	number_format_valuesdecimal_two_places                              number_format_values = 2
	number_format_valuesthousands_separator                             number_format_values = 3
	number_format_valuesthousands_separator_two_decimals                number_format_values = 4
	number_format_valuescurrency_no_decimals                            number_format_values = 5
	number_format_valuescurrency_no_decimals_red                        number_format_values = 6
	number_format_valuescurrency_two_decimals                           number_format_values = 7
	number_format_valuescurrency_two_decimals_red                       number_format_values = 8
	number_format_valuespercentage                                      number_format_values = 9
	number_format_valuespercentage_two_decimals                         number_format_values = 10
	number_format_valuesscientific                                      number_format_values = 11
	number_format_valuesfraction_one_digit                              number_format_values = 12
	number_format_valuesfraction_two_digits                             number_format_values = 13
	number_format_valuesdate_mmddyy                                     number_format_values = 14
	number_format_valuesdate_dmmmyy                                     number_format_values = 15
	number_format_valuesdate_dmmm                                       number_format_values = 16
	number_format_valuesdate_mmmyy                                      number_format_values = 17
	number_format_valuestime_12_hour                                    number_format_values = 18
	number_format_valuestime_12_hour_with_seconds                       number_format_values = 19
	number_format_valuestime_24_hour                                    number_format_values = 20
	number_format_valuestime_24_hour_with_seconds                       number_format_values = 21
	number_format_valuesdate_time_mmddyy                                number_format_values = 22
	number_format_valuesaccounting_no_decimals                          number_format_values = 23
	number_format_valuesaccounting_no_decimals_red                      number_format_values = 24
	number_format_valuesaccounting_two_decimals                         number_format_values = 25
	number_format_valuesaccounting_two_decimals_red                     number_format_values = 26
	number_format_valuesaccounting_negative_in_parentheses              number_format_values = 27
	number_format_valuesaccounting_two_decimals_negative_in_parentheses number_format_values = 28
	number_format_valuesaccounting_aligned_symbols                      number_format_values = 29
	number_format_valuesaccounting_aligned_symbols_two_decimals         number_format_values = 30
	number_format_valuestime_minutes_seconds                            number_format_values = 31
	number_format_valuestime_hours_minutes_seconds                      number_format_values = 32
	number_format_valueselapsed_time_with_fractions                     number_format_values = 33
	number_format_valuesscientific_one_decimal                          number_format_values = 34
	number_format_valuestext_format                                     number_format_values = 35
	number_format_valuescustom                                          number_format_values = 36
)

var EnumNamesnumber_format_values = map[number_format_values]string{
	number_format_valuesgeneral:                                         "general",
	number_format_valuesinteger:                                         "integer",
	number_format_valuesdecimal_two_places:                              "decimal_two_places",
	number_format_valuesthousands_separator:                             "thousands_separator",
	number_format_valuesthousands_separator_two_decimals:                "thousands_separator_two_decimals",
	number_format_valuescurrency_no_decimals:                            "currency_no_decimals",
	number_format_valuescurrency_no_decimals_red:                        "currency_no_decimals_red",
	number_format_valuescurrency_two_decimals:                           "currency_two_decimals",
	number_format_valuescurrency_two_decimals_red:                       "currency_two_decimals_red",
	number_format_valuespercentage:                                      "percentage",
	number_format_valuespercentage_two_decimals:                         "percentage_two_decimals",
	number_format_valuesscientific:                                      "scientific",
	number_format_valuesfraction_one_digit:                              "fraction_one_digit",
	number_format_valuesfraction_two_digits:                             "fraction_two_digits",
	number_format_valuesdate_mmddyy:                                     "date_mmddyy",
	number_format_valuesdate_dmmmyy:                                     "date_dmmmyy",
	number_format_valuesdate_dmmm:                                       "date_dmmm",
	number_format_valuesdate_mmmyy:                                      "date_mmmyy",
	number_format_valuestime_12_hour:                                    "time_12_hour",
	number_format_valuestime_12_hour_with_seconds:                       "time_12_hour_with_seconds",
	number_format_valuestime_24_hour:                                    "time_24_hour",
	number_format_valuestime_24_hour_with_seconds:                       "time_24_hour_with_seconds",
	number_format_valuesdate_time_mmddyy:                                "date_time_mmddyy",
	number_format_valuesaccounting_no_decimals:                          "accounting_no_decimals",
	number_format_valuesaccounting_no_decimals_red:                      "accounting_no_decimals_red",
	number_format_valuesaccounting_two_decimals:                         "accounting_two_decimals",
	number_format_valuesaccounting_two_decimals_red:                     "accounting_two_decimals_red",
	number_format_valuesaccounting_negative_in_parentheses:              "accounting_negative_in_parentheses",
	number_format_valuesaccounting_two_decimals_negative_in_parentheses: "accounting_two_decimals_negative_in_parentheses",
	number_format_valuesaccounting_aligned_symbols:                      "accounting_aligned_symbols",
	number_format_valuesaccounting_aligned_symbols_two_decimals:         "accounting_aligned_symbols_two_decimals",
	number_format_valuestime_minutes_seconds:                            "time_minutes_seconds",
	number_format_valuestime_hours_minutes_seconds:                      "time_hours_minutes_seconds",
	number_format_valueselapsed_time_with_fractions:                     "elapsed_time_with_fractions",
	number_format_valuesscientific_one_decimal:                          "scientific_one_decimal",
	number_format_valuestext_format:                                     "text_format",
	number_format_valuescustom:                                          "custom",
}

var EnumValuesnumber_format_values = map[string]number_format_values{
	"general":                                         number_format_valuesgeneral,
	"integer":                                         number_format_valuesinteger,
	"decimal_two_places":                              number_format_valuesdecimal_two_places,
	"thousands_separator":                             number_format_valuesthousands_separator,
	"thousands_separator_two_decimals":                number_format_valuesthousands_separator_two_decimals,
	"currency_no_decimals":                            number_format_valuescurrency_no_decimals,
	"currency_no_decimals_red":                        number_format_valuescurrency_no_decimals_red,
	"currency_two_decimals":                           number_format_valuescurrency_two_decimals,
	"currency_two_decimals_red":                       number_format_valuescurrency_two_decimals_red,
	"percentage":                                      number_format_valuespercentage,
	"percentage_two_decimals":                         number_format_valuespercentage_two_decimals,
	"scientific":                                      number_format_valuesscientific,
	"fraction_one_digit":                              number_format_valuesfraction_one_digit,
	"fraction_two_digits":                             number_format_valuesfraction_two_digits,
	"date_mmddyy":                                     number_format_valuesdate_mmddyy,
	"date_dmmmyy":                                     number_format_valuesdate_dmmmyy,
	"date_dmmm":                                       number_format_valuesdate_dmmm,
	"date_mmmyy":                                      number_format_valuesdate_mmmyy,
	"time_12_hour":                                    number_format_valuestime_12_hour,
	"time_12_hour_with_seconds":                       number_format_valuestime_12_hour_with_seconds,
	"time_24_hour":                                    number_format_valuestime_24_hour,
	"time_24_hour_with_seconds":                       number_format_valuestime_24_hour_with_seconds,
	"date_time_mmddyy":                                number_format_valuesdate_time_mmddyy,
	"accounting_no_decimals":                          number_format_valuesaccounting_no_decimals,
	"accounting_no_decimals_red":                      number_format_valuesaccounting_no_decimals_red,
	"accounting_two_decimals":                         number_format_valuesaccounting_two_decimals,
	"accounting_two_decimals_red":                     number_format_valuesaccounting_two_decimals_red,
	"accounting_negative_in_parentheses":              number_format_valuesaccounting_negative_in_parentheses,
	"accounting_two_decimals_negative_in_parentheses": number_format_valuesaccounting_two_decimals_negative_in_parentheses,
	"accounting_aligned_symbols":                      number_format_valuesaccounting_aligned_symbols,
	"accounting_aligned_symbols_two_decimals":         number_format_valuesaccounting_aligned_symbols_two_decimals,
	"time_minutes_seconds":                            number_format_valuestime_minutes_seconds,
	"time_hours_minutes_seconds":                      number_format_valuestime_hours_minutes_seconds,
	"elapsed_time_with_fractions":                     number_format_valueselapsed_time_with_fractions,
	"scientific_one_decimal":                          number_format_valuesscientific_one_decimal,
	"text_format":                                     number_format_valuestext_format,
	"custom":                                          number_format_valuescustom,
}

func (v number_format_values) String() string {
	if s, ok := EnumNamesnumber_format_values[v]; ok {
		return s
	}
	return "number_format_values(" + strconv.FormatInt(int64(v), 10) + ")"
}
