// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import "strconv"

type Number_format_values int32

const (
	Number_format_valuesgeneral                                         Number_format_values = 0
	Number_format_valuesinteger                                         Number_format_values = 1
	Number_format_valuesdecimal_two_places                              Number_format_values = 2
	Number_format_valuesthousands_separator                             Number_format_values = 3
	Number_format_valuesthousands_separator_two_decimals                Number_format_values = 4
	Number_format_valuescurrency_no_decimals                            Number_format_values = 5
	Number_format_valuescurrency_no_decimals_red                        Number_format_values = 6
	Number_format_valuescurrency_two_decimals                           Number_format_values = 7
	Number_format_valuescurrency_two_decimals_red                       Number_format_values = 8
	Number_format_valuespercentage                                      Number_format_values = 9
	Number_format_valuespercentage_two_decimals                         Number_format_values = 10
	Number_format_valuesscientific                                      Number_format_values = 11
	Number_format_valuesfraction_one_digit                              Number_format_values = 12
	Number_format_valuesfraction_two_digits                             Number_format_values = 13
	Number_format_valuesdate_mmddyy                                     Number_format_values = 14
	Number_format_valuesdate_dmmmyy                                     Number_format_values = 15
	Number_format_valuesdate_dmmm                                       Number_format_values = 16
	Number_format_valuesdate_mmmyy                                      Number_format_values = 17
	Number_format_valuestime_12_hour                                    Number_format_values = 18
	Number_format_valuestime_12_hour_with_seconds                       Number_format_values = 19
	Number_format_valuestime_24_hour                                    Number_format_values = 20
	Number_format_valuestime_24_hour_with_seconds                       Number_format_values = 21
	Number_format_valuesdate_time_mmddyy                                Number_format_values = 22
	Number_format_valuesaccounting_no_decimals                          Number_format_values = 23
	Number_format_valuesaccounting_no_decimals_red                      Number_format_values = 24
	Number_format_valuesaccounting_two_decimals                         Number_format_values = 25
	Number_format_valuesaccounting_two_decimals_red                     Number_format_values = 26
	Number_format_valuesaccounting_negative_in_parentheses              Number_format_values = 27
	Number_format_valuesaccounting_two_decimals_negative_in_parentheses Number_format_values = 28
	Number_format_valuesaccounting_aligned_symbols                      Number_format_values = 29
	Number_format_valuesaccounting_aligned_symbols_two_decimals         Number_format_values = 30
	Number_format_valuestime_minutes_seconds                            Number_format_values = 31
	Number_format_valuestime_hours_minutes_seconds                      Number_format_values = 32
	Number_format_valueselapsed_time_with_fractions                     Number_format_values = 33
	Number_format_valuesscientific_one_decimal                          Number_format_values = 34
	Number_format_valuestext_format                                     Number_format_values = 35
	Number_format_valuescustom                                          Number_format_values = 36
)

var EnumNamesNumber_format_values = map[Number_format_values]string{
	Number_format_valuesgeneral:                                         "general",
	Number_format_valuesinteger:                                         "integer",
	Number_format_valuesdecimal_two_places:                              "decimal_two_places",
	Number_format_valuesthousands_separator:                             "thousands_separator",
	Number_format_valuesthousands_separator_two_decimals:                "thousands_separator_two_decimals",
	Number_format_valuescurrency_no_decimals:                            "currency_no_decimals",
	Number_format_valuescurrency_no_decimals_red:                        "currency_no_decimals_red",
	Number_format_valuescurrency_two_decimals:                           "currency_two_decimals",
	Number_format_valuescurrency_two_decimals_red:                       "currency_two_decimals_red",
	Number_format_valuespercentage:                                      "percentage",
	Number_format_valuespercentage_two_decimals:                         "percentage_two_decimals",
	Number_format_valuesscientific:                                      "scientific",
	Number_format_valuesfraction_one_digit:                              "fraction_one_digit",
	Number_format_valuesfraction_two_digits:                             "fraction_two_digits",
	Number_format_valuesdate_mmddyy:                                     "date_mmddyy",
	Number_format_valuesdate_dmmmyy:                                     "date_dmmmyy",
	Number_format_valuesdate_dmmm:                                       "date_dmmm",
	Number_format_valuesdate_mmmyy:                                      "date_mmmyy",
	Number_format_valuestime_12_hour:                                    "time_12_hour",
	Number_format_valuestime_12_hour_with_seconds:                       "time_12_hour_with_seconds",
	Number_format_valuestime_24_hour:                                    "time_24_hour",
	Number_format_valuestime_24_hour_with_seconds:                       "time_24_hour_with_seconds",
	Number_format_valuesdate_time_mmddyy:                                "date_time_mmddyy",
	Number_format_valuesaccounting_no_decimals:                          "accounting_no_decimals",
	Number_format_valuesaccounting_no_decimals_red:                      "accounting_no_decimals_red",
	Number_format_valuesaccounting_two_decimals:                         "accounting_two_decimals",
	Number_format_valuesaccounting_two_decimals_red:                     "accounting_two_decimals_red",
	Number_format_valuesaccounting_negative_in_parentheses:              "accounting_negative_in_parentheses",
	Number_format_valuesaccounting_two_decimals_negative_in_parentheses: "accounting_two_decimals_negative_in_parentheses",
	Number_format_valuesaccounting_aligned_symbols:                      "accounting_aligned_symbols",
	Number_format_valuesaccounting_aligned_symbols_two_decimals:         "accounting_aligned_symbols_two_decimals",
	Number_format_valuestime_minutes_seconds:                            "time_minutes_seconds",
	Number_format_valuestime_hours_minutes_seconds:                      "time_hours_minutes_seconds",
	Number_format_valueselapsed_time_with_fractions:                     "elapsed_time_with_fractions",
	Number_format_valuesscientific_one_decimal:                          "scientific_one_decimal",
	Number_format_valuestext_format:                                     "text_format",
	Number_format_valuescustom:                                          "custom",
}

var EnumValuesNumber_format_values = map[string]Number_format_values{
	"general":                                         Number_format_valuesgeneral,
	"integer":                                         Number_format_valuesinteger,
	"decimal_two_places":                              Number_format_valuesdecimal_two_places,
	"thousands_separator":                             Number_format_valuesthousands_separator,
	"thousands_separator_two_decimals":                Number_format_valuesthousands_separator_two_decimals,
	"currency_no_decimals":                            Number_format_valuescurrency_no_decimals,
	"currency_no_decimals_red":                        Number_format_valuescurrency_no_decimals_red,
	"currency_two_decimals":                           Number_format_valuescurrency_two_decimals,
	"currency_two_decimals_red":                       Number_format_valuescurrency_two_decimals_red,
	"percentage":                                      Number_format_valuespercentage,
	"percentage_two_decimals":                         Number_format_valuespercentage_two_decimals,
	"scientific":                                      Number_format_valuesscientific,
	"fraction_one_digit":                              Number_format_valuesfraction_one_digit,
	"fraction_two_digits":                             Number_format_valuesfraction_two_digits,
	"date_mmddyy":                                     Number_format_valuesdate_mmddyy,
	"date_dmmmyy":                                     Number_format_valuesdate_dmmmyy,
	"date_dmmm":                                       Number_format_valuesdate_dmmm,
	"date_mmmyy":                                      Number_format_valuesdate_mmmyy,
	"time_12_hour":                                    Number_format_valuestime_12_hour,
	"time_12_hour_with_seconds":                       Number_format_valuestime_12_hour_with_seconds,
	"time_24_hour":                                    Number_format_valuestime_24_hour,
	"time_24_hour_with_seconds":                       Number_format_valuestime_24_hour_with_seconds,
	"date_time_mmddyy":                                Number_format_valuesdate_time_mmddyy,
	"accounting_no_decimals":                          Number_format_valuesaccounting_no_decimals,
	"accounting_no_decimals_red":                      Number_format_valuesaccounting_no_decimals_red,
	"accounting_two_decimals":                         Number_format_valuesaccounting_two_decimals,
	"accounting_two_decimals_red":                     Number_format_valuesaccounting_two_decimals_red,
	"accounting_negative_in_parentheses":              Number_format_valuesaccounting_negative_in_parentheses,
	"accounting_two_decimals_negative_in_parentheses": Number_format_valuesaccounting_two_decimals_negative_in_parentheses,
	"accounting_aligned_symbols":                      Number_format_valuesaccounting_aligned_symbols,
	"accounting_aligned_symbols_two_decimals":         Number_format_valuesaccounting_aligned_symbols_two_decimals,
	"time_minutes_seconds":                            Number_format_valuestime_minutes_seconds,
	"time_hours_minutes_seconds":                      Number_format_valuestime_hours_minutes_seconds,
	"elapsed_time_with_fractions":                     Number_format_valueselapsed_time_with_fractions,
	"scientific_one_decimal":                          Number_format_valuesscientific_one_decimal,
	"text_format":                                     Number_format_valuestext_format,
	"custom":                                          Number_format_valuescustom,
}

func (v Number_format_values) String() string {
	if s, ok := EnumNamesNumber_format_values[v]; ok {
		return s
	}
	return "Number_format_values(" + strconv.FormatInt(int64(v), 10) + ")"
}
