// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import "strconv"

type Vertical_alignment_values int32

const (
	Vertical_alignment_valuesnone   Vertical_alignment_values = 0
	Vertical_alignment_valuestop    Vertical_alignment_values = 1
	Vertical_alignment_valuesmiddle Vertical_alignment_values = 2
	Vertical_alignment_valuesbottom Vertical_alignment_values = 3
)

var EnumNamesVertical_alignment_values = map[Vertical_alignment_values]string{
	Vertical_alignment_valuesnone:   "none",
	Vertical_alignment_valuestop:    "top",
	Vertical_alignment_valuesmiddle: "middle",
	Vertical_alignment_valuesbottom: "bottom",
}

var EnumValuesVertical_alignment_values = map[string]Vertical_alignment_values{
	"none":   Vertical_alignment_valuesnone,
	"top":    Vertical_alignment_valuestop,
	"middle": Vertical_alignment_valuesmiddle,
	"bottom": Vertical_alignment_valuesbottom,
}

func (v Vertical_alignment_values) String() string {
	if s, ok := EnumNamesVertical_alignment_values[v]; ok {
		return s
	}
	return "Vertical_alignment_values(" + strconv.FormatInt(int64(v), 10) + ")"
}
