// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import "strconv"

type vertical_alignment_values int32

const (
	vertical_alignment_valuesnone   vertical_alignment_values = 0
	vertical_alignment_valuestop    vertical_alignment_values = 1
	vertical_alignment_valuesmiddle vertical_alignment_values = 2
	vertical_alignment_valuesbottom vertical_alignment_values = 3
)

var EnumNamesvertical_alignment_values = map[vertical_alignment_values]string{
	vertical_alignment_valuesnone:   "none",
	vertical_alignment_valuestop:    "top",
	vertical_alignment_valuesmiddle: "middle",
	vertical_alignment_valuesbottom: "bottom",
}

var EnumValuesvertical_alignment_values = map[string]vertical_alignment_values{
	"none":   vertical_alignment_valuesnone,
	"top":    vertical_alignment_valuestop,
	"middle": vertical_alignment_valuesmiddle,
	"bottom": vertical_alignment_valuesbottom,
}

func (v vertical_alignment_values) String() string {
	if s, ok := EnumNamesvertical_alignment_values[v]; ok {
		return s
	}
	return "vertical_alignment_values(" + strconv.FormatInt(int64(v), 10) + ")"
}
