// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Worksheet_list_hyperlinks struct {
	_tab flatbuffers.Table
}

func GetRootAsWorksheet_list_hyperlinks(buf []byte, offset flatbuffers.UOffsetT) *Worksheet_list_hyperlinks {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Worksheet_list_hyperlinks{}
	x.Init(buf, n+offset)
	return x
}

func FinishWorksheet_list_hyperlinksBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWorksheet_list_hyperlinks(buf []byte, offset flatbuffers.UOffsetT) *Worksheet_list_hyperlinks {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Worksheet_list_hyperlinks{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWorksheet_list_hyperlinksBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Worksheet_list_hyperlinks) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Worksheet_list_hyperlinks) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Worksheet_list_hyperlinks) WorksheetPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Worksheet_list_hyperlinks) MutateWorksheetPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func Worksheet_list_hyperlinksStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func Worksheet_list_hyperlinksAddWorksheetPtr(builder *flatbuffers.Builder, worksheetPtr uint64) {
	builder.PrependUint64Slot(0, worksheetPtr, 0)
}
func Worksheet_list_hyperlinksEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
