// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Worksheet_add_picture struct {
	_tab flatbuffers.Table
}

func GetRootAsWorksheet_add_picture(buf []byte, offset flatbuffers.UOffsetT) *Worksheet_add_picture {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Worksheet_add_picture{}
	x.Init(buf, n+offset)
	return x
}

func FinishWorksheet_add_pictureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWorksheet_add_picture(buf []byte, offset flatbuffers.UOffsetT) *Worksheet_add_picture {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Worksheet_add_picture{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWorksheet_add_pictureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Worksheet_add_picture) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Worksheet_add_picture) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Worksheet_add_picture) WorksheetPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Worksheet_add_picture) MutateWorksheetPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Worksheet_add_picture) ImagePath() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Worksheet_add_picture) PictureSetting(obj *Worksheet_picture_setting) *Worksheet_picture_setting {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Worksheet_picture_setting)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func Worksheet_add_pictureStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func Worksheet_add_pictureAddWorksheetPtr(builder *flatbuffers.Builder, worksheetPtr uint64) {
	builder.PrependUint64Slot(0, worksheetPtr, 0)
}
func Worksheet_add_pictureAddImagePath(builder *flatbuffers.Builder, imagePath flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(imagePath), 0)
}
func Worksheet_add_pictureAddPictureSetting(builder *flatbuffers.Builder, pictureSetting flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(pictureSetting), 0)
}
func Worksheet_add_pictureEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
