// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import "strconv"

type worksheet_cell_data_type int8

const (
	worksheet_cell_data_typeauto          worksheet_cell_data_type = 0
	worksheet_cell_data_typenumber        worksheet_cell_data_type = 1
	worksheet_cell_data_typeboolean       worksheet_cell_data_type = 2
	worksheet_cell_data_typestring        worksheet_cell_data_type = 3
	worksheet_cell_data_typeshared_string worksheet_cell_data_type = 4
	worksheet_cell_data_typeinline_string worksheet_cell_data_type = 5
	worksheet_cell_data_typeerror         worksheet_cell_data_type = 6
)

var EnumNamesworksheet_cell_data_type = map[worksheet_cell_data_type]string{
	worksheet_cell_data_typeauto:          "auto",
	worksheet_cell_data_typenumber:        "number",
	worksheet_cell_data_typeboolean:       "boolean",
	worksheet_cell_data_typestring:        "string",
	worksheet_cell_data_typeshared_string: "shared_string",
	worksheet_cell_data_typeinline_string: "inline_string",
	worksheet_cell_data_typeerror:         "error",
}

var EnumValuesworksheet_cell_data_type = map[string]worksheet_cell_data_type{
	"auto":          worksheet_cell_data_typeauto,
	"number":        worksheet_cell_data_typenumber,
	"boolean":       worksheet_cell_data_typeboolean,
	"string":        worksheet_cell_data_typestring,
	"shared_string": worksheet_cell_data_typeshared_string,
	"inline_string": worksheet_cell_data_typeinline_string,
	"error":         worksheet_cell_data_typeerror,
}

func (v worksheet_cell_data_type) String() string {
	if s, ok := EnumNamesworksheet_cell_data_type[v]; ok {
		return s
	}
	return "worksheet_cell_data_type(" + strconv.FormatInt(int64(v), 10) + ")"
}
