// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import "strconv"

type worksheet_image_type int8

const (
	worksheet_image_typejpeg worksheet_image_type = 0
	worksheet_image_typepng  worksheet_image_type = 1
	worksheet_image_typegif  worksheet_image_type = 2
	worksheet_image_typebmp  worksheet_image_type = 3
	worksheet_image_typetiff worksheet_image_type = 4
)

var EnumNamesworksheet_image_type = map[worksheet_image_type]string{
	worksheet_image_typejpeg: "jpeg",
	worksheet_image_typepng:  "png",
	worksheet_image_typegif:  "gif",
	worksheet_image_typebmp:  "bmp",
	worksheet_image_typetiff: "tiff",
}

var EnumValuesworksheet_image_type = map[string]worksheet_image_type{
	"jpeg": worksheet_image_typejpeg,
	"png":  worksheet_image_typepng,
	"gif":  worksheet_image_typegif,
	"bmp":  worksheet_image_typebmp,
	"tiff": worksheet_image_typetiff,
}

func (v worksheet_image_type) String() string {
	if s, ok := EnumNamesworksheet_image_type[v]; ok {
		return s
	}
	return "worksheet_image_type(" + strconv.FormatInt(int64(v), 10) + ")"
}
