// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type worksheet_cell_package struct {
	_tab flatbuffers.Table
}

func GetRootAsworksheet_cell_package(buf []byte, offset flatbuffers.UOffsetT) *worksheet_cell_package {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &worksheet_cell_package{}
	x.Init(buf, n+offset)
	return x
}

func Finishworksheet_cell_packageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsworksheet_cell_package(buf []byte, offset flatbuffers.UOffsetT) *worksheet_cell_package {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &worksheet_cell_package{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedworksheet_cell_packageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *worksheet_cell_package) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *worksheet_cell_package) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *worksheet_cell_package) CellRef() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *worksheet_cell_package) RowIndex() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *worksheet_cell_package) MutateRowIndex(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *worksheet_cell_package) ColumnIndex() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *worksheet_cell_package) MutateColumnIndex(n uint16) bool {
	return rcv._tab.MutateUint16Slot(8, n)
}

func (rcv *worksheet_cell_package) CellProperty(obj *worksheet_cell_property) *worksheet_cell_property {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(worksheet_cell_property)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func worksheet_cell_packageStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func worksheet_cell_packageAddCellRef(builder *flatbuffers.Builder, cellRef flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(cellRef), 0)
}
func worksheet_cell_packageAddRowIndex(builder *flatbuffers.Builder, rowIndex uint32) {
	builder.PrependUint32Slot(1, rowIndex, 0)
}
func worksheet_cell_packageAddColumnIndex(builder *flatbuffers.Builder, columnIndex uint16) {
	builder.PrependUint16Slot(2, columnIndex, 0)
}
func worksheet_cell_packageAddCellProperty(builder *flatbuffers.Builder, cellProperty flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(cellProperty), 0)
}
func worksheet_cell_packageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
