// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Worksheet_cell_property struct {
	_tab flatbuffers.Table
}

func GetRootAsWorksheet_cell_property(buf []byte, offset flatbuffers.UOffsetT) *Worksheet_cell_property {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Worksheet_cell_property{}
	x.Init(buf, n+offset)
	return x
}

func FinishWorksheet_cell_propertyBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWorksheet_cell_property(buf []byte, offset flatbuffers.UOffsetT) *Worksheet_cell_property {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Worksheet_cell_property{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWorksheet_cell_propertyBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Worksheet_cell_property) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Worksheet_cell_property) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Worksheet_cell_property) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Worksheet_cell_property) Formula() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Worksheet_cell_property) DataType() Worksheet_cell_data_type {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return Worksheet_cell_data_type(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Worksheet_cell_property) MutateDataType(n Worksheet_cell_data_type) bool {
	return rcv._tab.MutateInt8Slot(8, int8(n))
}

func (rcv *Worksheet_cell_property) StyleIdPtr() *uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		v := rcv._tab.GetUint64(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *Worksheet_cell_property) MutateStyleIdPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func Worksheet_cell_propertyStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func Worksheet_cell_propertyAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(value), 0)
}
func Worksheet_cell_propertyAddFormula(builder *flatbuffers.Builder, formula flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(formula), 0)
}
func Worksheet_cell_propertyAddDataType(builder *flatbuffers.Builder, dataType Worksheet_cell_data_type) {
	builder.PrependInt8Slot(2, int8(dataType), 0)
}
func Worksheet_cell_propertyAddStyleIdPtr(builder *flatbuffers.Builder, styleIdPtr uint64) {
	builder.PrependUint64(styleIdPtr)
	builder.Slot(3)
}
func Worksheet_cell_propertyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
