// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Worksheet_set_cell_ref_value struct {
	_tab flatbuffers.Table
}

func GetRootAsWorksheet_set_cell_ref_value(buf []byte, offset flatbuffers.UOffsetT) *Worksheet_set_cell_ref_value {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Worksheet_set_cell_ref_value{}
	x.Init(buf, n+offset)
	return x
}

func FinishWorksheet_set_cell_ref_valueBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWorksheet_set_cell_ref_value(buf []byte, offset flatbuffers.UOffsetT) *Worksheet_set_cell_ref_value {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Worksheet_set_cell_ref_value{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWorksheet_set_cell_ref_valueBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Worksheet_set_cell_ref_value) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Worksheet_set_cell_ref_value) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Worksheet_set_cell_ref_value) WorksheetPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Worksheet_set_cell_ref_value) MutateWorksheetPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Worksheet_set_cell_ref_value) CellRef() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Worksheet_set_cell_ref_value) ColumnCells(obj *Worksheet_cell_property, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Worksheet_set_cell_ref_value) ColumnCellsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func Worksheet_set_cell_ref_valueStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func Worksheet_set_cell_ref_valueAddWorksheetPtr(builder *flatbuffers.Builder, worksheetPtr uint64) {
	builder.PrependUint64Slot(0, worksheetPtr, 0)
}
func Worksheet_set_cell_ref_valueAddCellRef(builder *flatbuffers.Builder, cellRef flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(cellRef), 0)
}
func Worksheet_set_cell_ref_valueAddColumnCells(builder *flatbuffers.Builder, columnCells flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(columnCells), 0)
}
func Worksheet_set_cell_ref_valueStartColumnCellsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func Worksheet_set_cell_ref_valueEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
