// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Worksheet_set_column_ref_properties struct {
	_tab flatbuffers.Table
}

func GetRootAsWorksheet_set_column_ref_properties(buf []byte, offset flatbuffers.UOffsetT) *Worksheet_set_column_ref_properties {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Worksheet_set_column_ref_properties{}
	x.Init(buf, n+offset)
	return x
}

func FinishWorksheet_set_column_ref_propertiesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWorksheet_set_column_ref_properties(buf []byte, offset flatbuffers.UOffsetT) *Worksheet_set_column_ref_properties {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Worksheet_set_column_ref_properties{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWorksheet_set_column_ref_propertiesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Worksheet_set_column_ref_properties) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Worksheet_set_column_ref_properties) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Worksheet_set_column_ref_properties) WorksheetPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Worksheet_set_column_ref_properties) MutateWorksheetPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Worksheet_set_column_ref_properties) CellRef() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Worksheet_set_column_ref_properties) ColumnProperties(obj *Worksheet_column_properties) *Worksheet_column_properties {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Worksheet_column_properties)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func Worksheet_set_column_ref_propertiesStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func Worksheet_set_column_ref_propertiesAddWorksheetPtr(builder *flatbuffers.Builder, worksheetPtr uint64) {
	builder.PrependUint64Slot(0, worksheetPtr, 0)
}
func Worksheet_set_column_ref_propertiesAddCellRef(builder *flatbuffers.Builder, cellRef flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(cellRef), 0)
}
func Worksheet_set_column_ref_propertiesAddColumnProperties(builder *flatbuffers.Builder, columnProperties flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(columnProperties), 0)
}
func Worksheet_set_column_ref_propertiesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
