// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type worksheet_get_range_cell_properties struct {
	_tab flatbuffers.Table
}

func GetRootAsworksheet_get_range_cell_properties(buf []byte, offset flatbuffers.UOffsetT) *worksheet_get_range_cell_properties {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &worksheet_get_range_cell_properties{}
	x.Init(buf, n+offset)
	return x
}

func Finishworksheet_get_range_cell_propertiesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsworksheet_get_range_cell_properties(buf []byte, offset flatbuffers.UOffsetT) *worksheet_get_range_cell_properties {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &worksheet_get_range_cell_properties{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedworksheet_get_range_cell_propertiesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *worksheet_get_range_cell_properties) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *worksheet_get_range_cell_properties) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *worksheet_get_range_cell_properties) WorksheetPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *worksheet_get_range_cell_properties) MutateWorksheetPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *worksheet_get_range_cell_properties) RefRange(obj *worksheet_reference_range) *worksheet_reference_range {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(worksheet_reference_range)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func worksheet_get_range_cell_propertiesStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func worksheet_get_range_cell_propertiesAddWorksheetPtr(builder *flatbuffers.Builder, worksheetPtr uint64) {
	builder.PrependUint64Slot(0, worksheetPtr, 0)
}
func worksheet_get_range_cell_propertiesAddRefRange(builder *flatbuffers.Builder, refRange flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(refRange), 0)
}
func worksheet_get_range_cell_propertiesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
