// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import "strconv"

type Worksheet_excel_hyperlink_type int8

const (
	Worksheet_excel_hyperlink_typeexisting_file Worksheet_excel_hyperlink_type = 0
	Worksheet_excel_hyperlink_typeweb_url       Worksheet_excel_hyperlink_type = 1
	Worksheet_excel_hyperlink_typetarget_sheet  Worksheet_excel_hyperlink_type = 2
)

var EnumNamesWorksheet_excel_hyperlink_type = map[Worksheet_excel_hyperlink_type]string{
	Worksheet_excel_hyperlink_typeexisting_file: "existing_file",
	Worksheet_excel_hyperlink_typeweb_url:       "web_url",
	Worksheet_excel_hyperlink_typetarget_sheet:  "target_sheet",
}

var EnumValuesWorksheet_excel_hyperlink_type = map[string]Worksheet_excel_hyperlink_type{
	"existing_file": Worksheet_excel_hyperlink_typeexisting_file,
	"web_url":       Worksheet_excel_hyperlink_typeweb_url,
	"target_sheet":  Worksheet_excel_hyperlink_typetarget_sheet,
}

func (v Worksheet_excel_hyperlink_type) String() string {
	if s, ok := EnumNamesWorksheet_excel_hyperlink_type[v]; ok {
		return s
	}
	return "Worksheet_excel_hyperlink_type(" + strconv.FormatInt(int64(v), 10) + ")"
}
