// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type worksheet_list_hyperlinks_return struct {
	_tab flatbuffers.Table
}

func GetRootAsworksheet_list_hyperlinks_return(buf []byte, offset flatbuffers.UOffsetT) *worksheet_list_hyperlinks_return {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &worksheet_list_hyperlinks_return{}
	x.Init(buf, n+offset)
	return x
}

func Finishworksheet_list_hyperlinks_returnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsworksheet_list_hyperlinks_return(buf []byte, offset flatbuffers.UOffsetT) *worksheet_list_hyperlinks_return {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &worksheet_list_hyperlinks_return{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedworksheet_list_hyperlinks_returnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *worksheet_list_hyperlinks_return) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *worksheet_list_hyperlinks_return) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *worksheet_list_hyperlinks_return) Hyperlinks(obj *worksheet_hyperlink, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *worksheet_list_hyperlinks_return) HyperlinksLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func worksheet_list_hyperlinks_returnStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func worksheet_list_hyperlinks_returnAddHyperlinks(builder *flatbuffers.Builder, hyperlinks flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(hyperlinks), 0)
}
func worksheet_list_hyperlinks_returnStartHyperlinksVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func worksheet_list_hyperlinks_returnEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
