// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type worksheet_excel_hyperlink struct {
	_tab flatbuffers.Table
}

func GetRootAsworksheet_excel_hyperlink(buf []byte, offset flatbuffers.UOffsetT) *worksheet_excel_hyperlink {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &worksheet_excel_hyperlink{}
	x.Init(buf, n+offset)
	return x
}

func Finishworksheet_excel_hyperlinkBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsworksheet_excel_hyperlink(buf []byte, offset flatbuffers.UOffsetT) *worksheet_excel_hyperlink {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &worksheet_excel_hyperlink{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedworksheet_excel_hyperlinkBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *worksheet_excel_hyperlink) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *worksheet_excel_hyperlink) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *worksheet_excel_hyperlink) Display() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *worksheet_excel_hyperlink) LinkType() worksheet_excel_hyperlink_type {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return worksheet_excel_hyperlink_type(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *worksheet_excel_hyperlink) MutateLinkType(n worksheet_excel_hyperlink_type) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func (rcv *worksheet_excel_hyperlink) Link() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func worksheet_excel_hyperlinkStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func worksheet_excel_hyperlinkAddDisplay(builder *flatbuffers.Builder, display flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(display), 0)
}
func worksheet_excel_hyperlinkAddLinkType(builder *flatbuffers.Builder, linkType worksheet_excel_hyperlink_type) {
	builder.PrependInt8Slot(1, int8(linkType), 0)
}
func worksheet_excel_hyperlinkAddLink(builder *flatbuffers.Builder, link flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(link), 0)
}
func worksheet_excel_hyperlinkEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
