// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type worksheet_set_cell_index_value struct {
	_tab flatbuffers.Table
}

func GetRootAsworksheet_set_cell_index_value(buf []byte, offset flatbuffers.UOffsetT) *worksheet_set_cell_index_value {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &worksheet_set_cell_index_value{}
	x.Init(buf, n+offset)
	return x
}

func Finishworksheet_set_cell_index_valueBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsworksheet_set_cell_index_value(buf []byte, offset flatbuffers.UOffsetT) *worksheet_set_cell_index_value {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &worksheet_set_cell_index_value{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedworksheet_set_cell_index_valueBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *worksheet_set_cell_index_value) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *worksheet_set_cell_index_value) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *worksheet_set_cell_index_value) WorksheetPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *worksheet_set_cell_index_value) MutateWorksheetPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *worksheet_set_cell_index_value) RowIndex() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *worksheet_set_cell_index_value) MutateRowIndex(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *worksheet_set_cell_index_value) ColumnIndex() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *worksheet_set_cell_index_value) MutateColumnIndex(n uint16) bool {
	return rcv._tab.MutateUint16Slot(8, n)
}

func (rcv *worksheet_set_cell_index_value) ColumnCells(obj *worksheet_cell_property, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *worksheet_set_cell_index_value) ColumnCellsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func worksheet_set_cell_index_valueStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func worksheet_set_cell_index_valueAddWorksheetPtr(builder *flatbuffers.Builder, worksheetPtr uint64) {
	builder.PrependUint64Slot(0, worksheetPtr, 0)
}
func worksheet_set_cell_index_valueAddRowIndex(builder *flatbuffers.Builder, rowIndex uint32) {
	builder.PrependUint32Slot(1, rowIndex, 0)
}
func worksheet_set_cell_index_valueAddColumnIndex(builder *flatbuffers.Builder, columnIndex uint16) {
	builder.PrependUint16Slot(2, columnIndex, 0)
}
func worksheet_set_cell_index_valueAddColumnCells(builder *flatbuffers.Builder, columnCells flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(columnCells), 0)
}
func worksheet_set_cell_index_valueStartColumnCellsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func worksheet_set_cell_index_valueEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
