// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type worksheet_list_merge_cell struct {
	_tab flatbuffers.Table
}

func GetRootAsworksheet_list_merge_cell(buf []byte, offset flatbuffers.UOffsetT) *worksheet_list_merge_cell {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &worksheet_list_merge_cell{}
	x.Init(buf, n+offset)
	return x
}

func Finishworksheet_list_merge_cellBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsworksheet_list_merge_cell(buf []byte, offset flatbuffers.UOffsetT) *worksheet_list_merge_cell {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &worksheet_list_merge_cell{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedworksheet_list_merge_cellBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *worksheet_list_merge_cell) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *worksheet_list_merge_cell) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *worksheet_list_merge_cell) WorksheetPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *worksheet_list_merge_cell) MutateWorksheetPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func worksheet_list_merge_cellStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func worksheet_list_merge_cellAddWorksheetPtr(builder *flatbuffers.Builder, worksheetPtr uint64) {
	builder.PrependUint64Slot(0, worksheetPtr, 0)
}
func worksheet_list_merge_cellEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
