// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Worksheet_column_properties struct {
	_tab flatbuffers.Table
}

func GetRootAsWorksheet_column_properties(buf []byte, offset flatbuffers.UOffsetT) *Worksheet_column_properties {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Worksheet_column_properties{}
	x.Init(buf, n+offset)
	return x
}

func FinishWorksheet_column_propertiesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWorksheet_column_properties(buf []byte, offset flatbuffers.UOffsetT) *Worksheet_column_properties {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Worksheet_column_properties{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWorksheet_column_propertiesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Worksheet_column_properties) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Worksheet_column_properties) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Worksheet_column_properties) Min() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Worksheet_column_properties) MutateMin(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *Worksheet_column_properties) Max() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Worksheet_column_properties) MutateMax(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *Worksheet_column_properties) Width() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *Worksheet_column_properties) MutateWidth(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *Worksheet_column_properties) Hidden() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *Worksheet_column_properties) MutateHidden(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *Worksheet_column_properties) BestFit() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *Worksheet_column_properties) MutateBestFit(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *Worksheet_column_properties) StyleIdPtr() *uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		v := rcv._tab.GetUint64(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *Worksheet_column_properties) MutateStyleIdPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func Worksheet_column_propertiesStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func Worksheet_column_propertiesAddMin(builder *flatbuffers.Builder, min uint32) {
	builder.PrependUint32Slot(0, min, 0)
}
func Worksheet_column_propertiesAddMax(builder *flatbuffers.Builder, max uint32) {
	builder.PrependUint32Slot(1, max, 0)
}
func Worksheet_column_propertiesAddWidth(builder *flatbuffers.Builder, width float32) {
	builder.PrependFloat32(width)
	builder.Slot(2)
}
func Worksheet_column_propertiesAddHidden(builder *flatbuffers.Builder, hidden bool) {
	builder.PrependBool(hidden)
	builder.Slot(3)
}
func Worksheet_column_propertiesAddBestFit(builder *flatbuffers.Builder, bestFit bool) {
	builder.PrependBool(bestFit)
	builder.Slot(4)
}
func Worksheet_column_propertiesAddStyleIdPtr(builder *flatbuffers.Builder, styleIdPtr uint64) {
	builder.PrependUint64(styleIdPtr)
	builder.Slot(5)
}
func Worksheet_column_propertiesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
