// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"

	openxml_office_fbs__global "openxml_office_fbs/global"
)

type worksheet_picture_setting struct {
	_tab flatbuffers.Table
}

func GetRootAsworksheet_picture_setting(buf []byte, offset flatbuffers.UOffsetT) *worksheet_picture_setting {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &worksheet_picture_setting{}
	x.Init(buf, n+offset)
	return x
}

func Finishworksheet_picture_settingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsworksheet_picture_setting(buf []byte, offset flatbuffers.UOffsetT) *worksheet_picture_setting {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &worksheet_picture_setting{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedworksheet_picture_settingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *worksheet_picture_setting) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *worksheet_picture_setting) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *worksheet_picture_setting) PictureSettings(obj *openxml_office_fbs__global.global_picture_settings) *openxml_office_fbs__global.global_picture_settings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(openxml_office_fbs__global.global_picture_settings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *worksheet_picture_setting) From(obj *worksheet_anchor_position) *worksheet_anchor_position {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(worksheet_anchor_position)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *worksheet_picture_setting) To(obj *worksheet_anchor_position) *worksheet_anchor_position {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(worksheet_anchor_position)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *worksheet_picture_setting) Hyperlink(obj *worksheet_excel_hyperlink) *worksheet_excel_hyperlink {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(worksheet_excel_hyperlink)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func worksheet_picture_settingStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func worksheet_picture_settingAddPictureSettings(builder *flatbuffers.Builder, pictureSettings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(pictureSettings), 0)
}
func worksheet_picture_settingAddFrom(builder *flatbuffers.Builder, from flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(from), 0)
}
func worksheet_picture_settingAddTo(builder *flatbuffers.Builder, to flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(to), 0)
}
func worksheet_picture_settingAddHyperlink(builder *flatbuffers.Builder, hyperlink flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(hyperlink), 0)
}
func worksheet_picture_settingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
