// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type worksheet_reference_range struct {
	_tab flatbuffers.Table
}

func GetRootAsworksheet_reference_range(buf []byte, offset flatbuffers.UOffsetT) *worksheet_reference_range {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &worksheet_reference_range{}
	x.Init(buf, n+offset)
	return x
}

func Finishworksheet_reference_rangeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsworksheet_reference_range(buf []byte, offset flatbuffers.UOffsetT) *worksheet_reference_range {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &worksheet_reference_range{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedworksheet_reference_rangeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *worksheet_reference_range) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *worksheet_reference_range) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *worksheet_reference_range) ColumnStart() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *worksheet_reference_range) MutateColumnStart(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *worksheet_reference_range) ColumnEnd() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *worksheet_reference_range) MutateColumnEnd(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func (rcv *worksheet_reference_range) RowStart() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *worksheet_reference_range) MutateRowStart(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *worksheet_reference_range) RowEnd() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *worksheet_reference_range) MutateRowEnd(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func worksheet_reference_rangeStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func worksheet_reference_rangeAddColumnStart(builder *flatbuffers.Builder, columnStart uint16) {
	builder.PrependUint16Slot(0, columnStart, 0)
}
func worksheet_reference_rangeAddColumnEnd(builder *flatbuffers.Builder, columnEnd uint16) {
	builder.PrependUint16Slot(1, columnEnd, 0)
}
func worksheet_reference_rangeAddRowStart(builder *flatbuffers.Builder, rowStart uint32) {
	builder.PrependUint32Slot(2, rowStart, 0)
}
func worksheet_reference_rangeAddRowEnd(builder *flatbuffers.Builder, rowEnd uint32) {
	builder.PrependUint32Slot(3, rowEnd, 0)
}
func worksheet_reference_rangeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
