// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Worksheet_set_hyperlink struct {
	_tab flatbuffers.Table
}

func GetRootAsWorksheet_set_hyperlink(buf []byte, offset flatbuffers.UOffsetT) *Worksheet_set_hyperlink {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Worksheet_set_hyperlink{}
	x.Init(buf, n+offset)
	return x
}

func FinishWorksheet_set_hyperlinkBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWorksheet_set_hyperlink(buf []byte, offset flatbuffers.UOffsetT) *Worksheet_set_hyperlink {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Worksheet_set_hyperlink{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWorksheet_set_hyperlinkBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Worksheet_set_hyperlink) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Worksheet_set_hyperlink) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Worksheet_set_hyperlink) WorksheetPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Worksheet_set_hyperlink) MutateWorksheetPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Worksheet_set_hyperlink) Display() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Worksheet_set_hyperlink) Link() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Worksheet_set_hyperlink) RefRange(obj *Worksheet_reference_range) *Worksheet_reference_range {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Worksheet_reference_range)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func Worksheet_set_hyperlinkStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func Worksheet_set_hyperlinkAddWorksheetPtr(builder *flatbuffers.Builder, worksheetPtr uint64) {
	builder.PrependUint64Slot(0, worksheetPtr, 0)
}
func Worksheet_set_hyperlinkAddDisplay(builder *flatbuffers.Builder, display flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(display), 0)
}
func Worksheet_set_hyperlinkAddLink(builder *flatbuffers.Builder, link flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(link), 0)
}
func Worksheet_set_hyperlinkAddRefRange(builder *flatbuffers.Builder, refRange flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(refRange), 0)
}
func Worksheet_set_hyperlinkEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
