// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type worksheet_hyperlink struct {
	_tab flatbuffers.Table
}

func GetRootAsworksheet_hyperlink(buf []byte, offset flatbuffers.UOffsetT) *worksheet_hyperlink {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &worksheet_hyperlink{}
	x.Init(buf, n+offset)
	return x
}

func Finishworksheet_hyperlinkBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsworksheet_hyperlink(buf []byte, offset flatbuffers.UOffsetT) *worksheet_hyperlink {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &worksheet_hyperlink{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedworksheet_hyperlinkBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *worksheet_hyperlink) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *worksheet_hyperlink) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *worksheet_hyperlink) Display() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *worksheet_hyperlink) Link() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *worksheet_hyperlink) RefRange(obj *worksheet_reference_range) *worksheet_reference_range {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(worksheet_reference_range)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func worksheet_hyperlinkStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func worksheet_hyperlinkAddDisplay(builder *flatbuffers.Builder, display flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(display), 0)
}
func worksheet_hyperlinkAddLink(builder *flatbuffers.Builder, link flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(link), 0)
}
func worksheet_hyperlinkAddRefRange(builder *flatbuffers.Builder, refRange flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(refRange), 0)
}
func worksheet_hyperlinkEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
