// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Worksheet_get_range_cell_properties_return struct {
	_tab flatbuffers.Table
}

func GetRootAsWorksheet_get_range_cell_properties_return(buf []byte, offset flatbuffers.UOffsetT) *Worksheet_get_range_cell_properties_return {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Worksheet_get_range_cell_properties_return{}
	x.Init(buf, n+offset)
	return x
}

func FinishWorksheet_get_range_cell_properties_returnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWorksheet_get_range_cell_properties_return(buf []byte, offset flatbuffers.UOffsetT) *Worksheet_get_range_cell_properties_return {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Worksheet_get_range_cell_properties_return{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWorksheet_get_range_cell_properties_returnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Worksheet_get_range_cell_properties_return) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Worksheet_get_range_cell_properties_return) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Worksheet_get_range_cell_properties_return) CellPackages(obj *Worksheet_cell_package, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Worksheet_get_range_cell_properties_return) CellPackagesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func Worksheet_get_range_cell_properties_returnStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func Worksheet_get_range_cell_properties_returnAddCellPackages(builder *flatbuffers.Builder, cellPackages flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(cellPackages), 0)
}
func Worksheet_get_range_cell_properties_returnStartCellPackagesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func Worksheet_get_range_cell_properties_returnEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
