// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import "strconv"

type Worksheet_cell_data_type int8

const (
	Worksheet_cell_data_typeauto          Worksheet_cell_data_type = 0
	Worksheet_cell_data_typenumber        Worksheet_cell_data_type = 1
	Worksheet_cell_data_typeboolean       Worksheet_cell_data_type = 2
	Worksheet_cell_data_typestring        Worksheet_cell_data_type = 3
	Worksheet_cell_data_typeshared_string Worksheet_cell_data_type = 4
	Worksheet_cell_data_typeinline_string Worksheet_cell_data_type = 5
	Worksheet_cell_data_typeerror         Worksheet_cell_data_type = 6
)

var EnumNamesWorksheet_cell_data_type = map[Worksheet_cell_data_type]string{
	Worksheet_cell_data_typeauto:          "auto",
	Worksheet_cell_data_typenumber:        "number",
	Worksheet_cell_data_typeboolean:       "boolean",
	Worksheet_cell_data_typestring:        "string",
	Worksheet_cell_data_typeshared_string: "shared_string",
	Worksheet_cell_data_typeinline_string: "inline_string",
	Worksheet_cell_data_typeerror:         "error",
}

var EnumValuesWorksheet_cell_data_type = map[string]Worksheet_cell_data_type{
	"auto":          Worksheet_cell_data_typeauto,
	"number":        Worksheet_cell_data_typenumber,
	"boolean":       Worksheet_cell_data_typeboolean,
	"string":        Worksheet_cell_data_typestring,
	"shared_string": Worksheet_cell_data_typeshared_string,
	"inline_string": Worksheet_cell_data_typeinline_string,
	"error":         Worksheet_cell_data_typeerror,
}

func (v Worksheet_cell_data_type) String() string {
	if s, ok := EnumNamesWorksheet_cell_data_type[v]; ok {
		return s
	}
	return "Worksheet_cell_data_type(" + strconv.FormatInt(int64(v), 10) + ")"
}
