// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type worksheet_row_properties struct {
	_tab flatbuffers.Table
}

func GetRootAsworksheet_row_properties(buf []byte, offset flatbuffers.UOffsetT) *worksheet_row_properties {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &worksheet_row_properties{}
	x.Init(buf, n+offset)
	return x
}

func Finishworksheet_row_propertiesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsworksheet_row_properties(buf []byte, offset flatbuffers.UOffsetT) *worksheet_row_properties {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &worksheet_row_properties{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedworksheet_row_propertiesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *worksheet_row_properties) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *worksheet_row_properties) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *worksheet_row_properties) Height() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *worksheet_row_properties) MutateHeight(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func (rcv *worksheet_row_properties) Hidden() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *worksheet_row_properties) MutateHidden(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *worksheet_row_properties) ThickTop() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *worksheet_row_properties) MutateThickTop(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *worksheet_row_properties) ThickBottom() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *worksheet_row_properties) MutateThickBottom(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *worksheet_row_properties) StyleIdPtr() *uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		v := rcv._tab.GetUint64(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *worksheet_row_properties) MutateStyleIdPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func worksheet_row_propertiesStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func worksheet_row_propertiesAddHeight(builder *flatbuffers.Builder, height float32) {
	builder.PrependFloat32(height)
	builder.Slot(0)
}
func worksheet_row_propertiesAddHidden(builder *flatbuffers.Builder, hidden bool) {
	builder.PrependBool(hidden)
	builder.Slot(1)
}
func worksheet_row_propertiesAddThickTop(builder *flatbuffers.Builder, thickTop bool) {
	builder.PrependBool(thickTop)
	builder.Slot(2)
}
func worksheet_row_propertiesAddThickBottom(builder *flatbuffers.Builder, thickBottom bool) {
	builder.PrependBool(thickBottom)
	builder.Slot(3)
}
func worksheet_row_propertiesAddStyleIdPtr(builder *flatbuffers.Builder, styleIdPtr uint64) {
	builder.PrependUint64(styleIdPtr)
	builder.Slot(4)
}
func worksheet_row_propertiesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
