// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Worksheet_delete_sheet struct {
	_tab flatbuffers.Table
}

func GetRootAsWorksheet_delete_sheet(buf []byte, offset flatbuffers.UOffsetT) *Worksheet_delete_sheet {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Worksheet_delete_sheet{}
	x.Init(buf, n+offset)
	return x
}

func FinishWorksheet_delete_sheetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWorksheet_delete_sheet(buf []byte, offset flatbuffers.UOffsetT) *Worksheet_delete_sheet {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Worksheet_delete_sheet{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWorksheet_delete_sheetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Worksheet_delete_sheet) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Worksheet_delete_sheet) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Worksheet_delete_sheet) WorksheetPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Worksheet_delete_sheet) MutateWorksheetPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func Worksheet_delete_sheetStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func Worksheet_delete_sheetAddWorksheetPtr(builder *flatbuffers.Builder, worksheetPtr uint64) {
	builder.PrependUint64Slot(0, worksheetPtr, 0)
}
func Worksheet_delete_sheetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
