// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import "strconv"

type worksheet_excel_hyperlink_type int8

const (
	worksheet_excel_hyperlink_typeexisting_file worksheet_excel_hyperlink_type = 0
	worksheet_excel_hyperlink_typeweb_url       worksheet_excel_hyperlink_type = 1
	worksheet_excel_hyperlink_typetarget_sheet  worksheet_excel_hyperlink_type = 2
)

var EnumNamesworksheet_excel_hyperlink_type = map[worksheet_excel_hyperlink_type]string{
	worksheet_excel_hyperlink_typeexisting_file: "existing_file",
	worksheet_excel_hyperlink_typeweb_url:       "web_url",
	worksheet_excel_hyperlink_typetarget_sheet:  "target_sheet",
}

var EnumValuesworksheet_excel_hyperlink_type = map[string]worksheet_excel_hyperlink_type{
	"existing_file": worksheet_excel_hyperlink_typeexisting_file,
	"web_url":       worksheet_excel_hyperlink_typeweb_url,
	"target_sheet":  worksheet_excel_hyperlink_typetarget_sheet,
}

func (v worksheet_excel_hyperlink_type) String() string {
	if s, ok := EnumNamesworksheet_excel_hyperlink_type[v]; ok {
		return s
	}
	return "worksheet_excel_hyperlink_type(" + strconv.FormatInt(int64(v), 10) + ")"
}
