// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package presentation_2007

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PresentationSettingsModel struct {
	_tab flatbuffers.Table
}

func GetRootAsPresentationSettingsModel(buf []byte, offset flatbuffers.UOffsetT) *PresentationSettingsModel {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PresentationSettingsModel{}
	x.Init(buf, n+offset)
	return x
}

func FinishPresentationSettingsModelBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPresentationSettingsModel(buf []byte, offset flatbuffers.UOffsetT) *PresentationSettingsModel {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PresentationSettingsModel{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPresentationSettingsModelBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PresentationSettingsModel) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PresentationSettingsModel) Table() flatbuffers.Table {
	return rcv._tab
}

func PresentationSettingsModelStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func PresentationSettingsModelEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
