use cbindgen::Config;
use std::path::Path;
use std::process::Command;
use std::{env, fs};

fn main() {
    if std::env::var("DEVOPS_BUILD").unwrap_or_default() == "1" {
        Command::new("git")
            .args(["fetch", "--tags", "--force"])
            .output()
            .expect("Failed to pull latest tags");
        // Get the latest Git tag matching "v*"
        let output = Command::new("git")
            .args(["describe", "--tags", "--match", "v*", "--abbrev=0"])
            .output()
            .expect("Failed to get latest Git tag");

        if !output.status.success() {
            panic!("Error retrieving Git tag");
        }

        let version = String::from_utf8(output.stdout)
            .unwrap()
            .trim()
            .replace("v", "");

        // Set as environment variable for Rust
        println!("cargo:rustc-env=GIT_VERSION={}", version);

        // Overwrite version in Cargo.toml (Optional)
        let cargo_toml_path = "Cargo.toml";
        let cargo_toml = fs::read_to_string(cargo_toml_path).expect("Failed to read Cargo.toml");
        let updated_cargo_toml = cargo_toml
            .lines()
            .map(|line| {
                if line.starts_with("version =") {
                    format!("version = \"{}\"", version)
                } else {
                    line.to_string()
                }
            })
            .collect::<Vec<_>>()
            .join("\n");

        fs::write(cargo_toml_path, updated_cargo_toml).expect("Failed to update Cargo.toml");

        println!("Updated Cargo.toml version to {}", version);
    }
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    let status = Command::new("flatc")
        .args(&[
            "-r",
            "--gen-all",
            "-o",
            &env::current_dir()
                .unwrap()
                .parent()
                .unwrap()
                .join("rs_ffi/src")
                .to_string_lossy(),
            &env::current_dir()
                .unwrap()
                .parent()
                .unwrap()
                .join("fbs/consolidated.fbs")
                .to_string_lossy(),
        ])
        .status()
        .expect("Failed to run flatc");

    if !status.success() {
        panic!("flatc failed with status: {:?}", status);
    }

    let methods = cbindgen::Builder::new()
        .with_crate(crate_dir.clone())
        .with_config(Config {
            language:cbindgen::Language::C,
            autogen_warning:Some("/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */".to_string()),
            header:Some("/* Dravia Vemal. MIT License */".to_string()),
            include_version:true,
            package_version:true,
            no_includes:true,
            ..Config::default()
        })
        .generate()
        .unwrap();
    methods.write_to_file(Path::new("../target").join("methods.h"));

    let headers = cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(Config {
            language:cbindgen::Language::C,
            autogen_warning:Some("/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */".to_string()),
            header:Some("/* Dravia Vemal. MIT License */".to_string()),
            include_version:true,
            package_version:true,
            ..Config::default()
        })
        .generate()
        .unwrap();
    headers.write_to_file(Path::new("../target").join("headers.h"));
}
