[package]
name = "draviavemal-openxml_office_ffi"
authors = ["Dravia Vemal"]
description = "FFI Interface crate for multi language support expansion"
license = "AGPL-3.0-only"
repository = "https://github.com/DraviaVemal/openxml-office"
documentation = "https://docs.draviavemal.com/openxml-office"
version = "4.0.0-alpha.18"
edition = "2021"
include = ["src/**", "Cargo.toml", "Cargo.lock", "README.md"]

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
draviavemal-openxml_office.workspace = true
flatbuffers.workspace = true
anyhow.workspace = true
log.workspace = true

[profile.dev]
debug = true

[build-dependencies]
cbindgen = "0.27.0"
