// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package presentation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type power_point_save_as struct {
	_tab flatbuffers.Table
}

func GetRootAspower_point_save_as(buf []byte, offset flatbuffers.UOffsetT) *power_point_save_as {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &power_point_save_as{}
	x.Init(buf, n+offset)
	return x
}

func Finishpower_point_save_asBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAspower_point_save_as(buf []byte, offset flatbuffers.UOffsetT) *power_point_save_as {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &power_point_save_as{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedpower_point_save_asBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *power_point_save_as) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *power_point_save_as) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *power_point_save_as) PowerPointPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *power_point_save_as) MutatePowerPointPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *power_point_save_as) FileName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func power_point_save_asStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func power_point_save_asAddPowerPointPtr(builder *flatbuffers.Builder, powerPointPtr uint64) {
	builder.PrependUint64Slot(0, powerPointPtr, 0)
}
func power_point_save_asAddFileName(builder *flatbuffers.Builder, fileName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(fileName), 0)
}
func power_point_save_asEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
