// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package presentation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Power_point_settings struct {
	_tab flatbuffers.Table
}

func GetRootAsPower_point_settings(buf []byte, offset flatbuffers.UOffsetT) *Power_point_settings {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Power_point_settings{}
	x.Init(buf, n+offset)
	return x
}

func FinishPower_point_settingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPower_point_settings(buf []byte, offset flatbuffers.UOffsetT) *Power_point_settings {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Power_point_settings{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPower_point_settingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Power_point_settings) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Power_point_settings) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Power_point_settings) IsEditable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Power_point_settings) MutateIsEditable(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func Power_point_settingsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func Power_point_settingsAddIsEditable(builder *flatbuffers.Builder, isEditable bool) {
	builder.PrependBoolSlot(0, isEditable, false)
}
func Power_point_settingsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
