// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package presentation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Power_point_create struct {
	_tab flatbuffers.Table
}

func GetRootAsPower_point_create(buf []byte, offset flatbuffers.UOffsetT) *Power_point_create {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Power_point_create{}
	x.Init(buf, n+offset)
	return x
}

func FinishPower_point_createBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPower_point_create(buf []byte, offset flatbuffers.UOffsetT) *Power_point_create {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Power_point_create{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPower_point_createBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Power_point_create) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Power_point_create) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Power_point_create) FileName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Power_point_create) PowerPointSettings(obj *Power_point_settings) *Power_point_settings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Power_point_settings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func Power_point_createStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func Power_point_createAddFileName(builder *flatbuffers.Builder, fileName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(fileName), 0)
}
func Power_point_createAddPowerPointSettings(builder *flatbuffers.Builder, powerPointSettings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(powerPointSettings), 0)
}
func Power_point_createEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
