namespace openxml_office_fbs.presentation;

// Power_point_create - Start

table Power_point_create {
    file_name: string;
    power_point_settings: Power_point_settings(required);
}

table Power_point_settings {
    is_editable: bool;
}

table Power_point_create_return {
    power_point_ptr: uint64;
}

// Power_point_create - End

// Power_point_save_as - Start

table Power_point_save_as {
    power_point_ptr: uint64;
    file_name: string;
}

table Power_point_save_as_return {
    full_path: string;
}

// Power_point_save_as - End