include "../global_2007/consolidated.fbs";

namespace openxml_office_fbs.spreadsheet_2007;

enum ColorSettingTypeValues : byte { 
    Indexed = 0,
    Theme = 1,
    Rgb = 2
}

enum BorderStyleValues : byte { 
    None = 0,
    Thin = 1,
    Thick = 2,
    Dotted = 3,
    Double = 4,
    Dashed = 5,
    DashDot = 6,
    DashDotDot = 7,
    Medium = 8,
    MediumDashed = 9,
    MediumDashDot = 10,
    MediumDashDotDot = 11,
    SlantDashDot = 12,
    Hair = 13,
}

enum HorizontalAlignmentValues : byte { 
    None = 0,
    LEFT = 1,
    CENTER = 2,
    RIGHT = 3,
    JUSTIFY = 4,
}

enum VerticalAlignmentValues : byte { 
    None = 0,
    Top = 1,
    Middle = 2,
    Bottom = 3,
}

enum PatternTypeValues : byte { 
    None = 0,
    Gray125 = 1,
    Solid = 2,
}

table ColorSetting {
    color_setting_type: ColorSettingTypeValues;
    value: string;
}

table BorderSetting {
    border_color: ColorSetting;
    style: BorderStyleValues;
}

table StyleSetting {
    number_format: ushort;
    custom_number_format: string;
    border_left: BorderSetting;
    border_top: BorderSetting;
    border_right: BorderSetting;
    border_bottom: BorderSetting;
    border_diagonal: BorderSetting;
    font_family: string;
    font_size: ubyte;
    text_color: ColorSetting;
    is_bold: bool;
    is_italic: bool;
    is_underline: bool;
    is_double_underline: bool;
    is_wrap_text: bool;
    background_color: string;
    foreground_color: string;
    pattern_type: PatternTypeValues;
    horizontal_alignment: HorizontalAlignmentValues;
    vertical_alignment: VerticalAlignmentValues;
    protect: bool;
}

root_type StyleSetting;
