// automatically generated by the FlatBuffers compiler, do not modify

package openxml_office.global_2007;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class CorePropertiesModel extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static CorePropertiesModel getRootAsCorePropertiesModel(ByteBuffer _bb) { return getRootAsCorePropertiesModel(_bb, new CorePropertiesModel()); }
  public static CorePropertiesModel getRootAsCorePropertiesModel(ByteBuffer _bb, CorePropertiesModel obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CorePropertiesModel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String title() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer titleAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer titleInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String subject() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer subjectAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer subjectInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String description() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer descriptionAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer descriptionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String tags() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tagsAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer tagsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String category() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer categoryAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer categoryInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String creator() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer creatorAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer creatorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }

  public static int createCorePropertiesModel(FlatBufferBuilder builder,
      int titleOffset,
      int subjectOffset,
      int descriptionOffset,
      int tagsOffset,
      int categoryOffset,
      int creatorOffset) {
    builder.startTable(6);
    CorePropertiesModel.addCreator(builder, creatorOffset);
    CorePropertiesModel.addCategory(builder, categoryOffset);
    CorePropertiesModel.addTags(builder, tagsOffset);
    CorePropertiesModel.addDescription(builder, descriptionOffset);
    CorePropertiesModel.addSubject(builder, subjectOffset);
    CorePropertiesModel.addTitle(builder, titleOffset);
    return CorePropertiesModel.endCorePropertiesModel(builder);
  }

  public static void startCorePropertiesModel(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addTitle(FlatBufferBuilder builder, int titleOffset) { builder.addOffset(0, titleOffset, 0); }
  public static void addSubject(FlatBufferBuilder builder, int subjectOffset) { builder.addOffset(1, subjectOffset, 0); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(2, descriptionOffset, 0); }
  public static void addTags(FlatBufferBuilder builder, int tagsOffset) { builder.addOffset(3, tagsOffset, 0); }
  public static void addCategory(FlatBufferBuilder builder, int categoryOffset) { builder.addOffset(4, categoryOffset, 0); }
  public static void addCreator(FlatBufferBuilder builder, int creatorOffset) { builder.addOffset(5, creatorOffset, 0); }
  public static int endCorePropertiesModel(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishCorePropertiesModelBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedCorePropertiesModelBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CorePropertiesModel get(int j) { return get(new CorePropertiesModel(), j); }
    public CorePropertiesModel get(CorePropertiesModel obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

