// automatically generated by the FlatBuffers compiler, do not modify

package openxml_office.global_2007;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ThemePalletModel extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static ThemePalletModel getRootAsThemePalletModel(ByteBuffer _bb) { return getRootAsThemePalletModel(_bb, new ThemePalletModel()); }
  public static ThemePalletModel getRootAsThemePalletModel(ByteBuffer _bb, ThemePalletModel obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ThemePalletModel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String accent1() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer accent1AsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer accent1InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String accent2() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer accent2AsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer accent2InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String accent3() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer accent3AsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer accent3InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String accent4() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer accent4AsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer accent4InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String accent5() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer accent5AsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer accent5InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String accent6() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer accent6AsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer accent6InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }
  public String dark1() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer dark1AsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer dark1InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }
  public String dark2() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer dark2AsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer dark2InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }
  public String light1() { int o = __offset(20); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer light1AsByteBuffer() { return __vector_as_bytebuffer(20, 1); }
  public ByteBuffer light1InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 20, 1); }
  public String light2() { int o = __offset(22); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer light2AsByteBuffer() { return __vector_as_bytebuffer(22, 1); }
  public ByteBuffer light2InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 22, 1); }
  public String hyperlink() { int o = __offset(24); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer hyperlinkAsByteBuffer() { return __vector_as_bytebuffer(24, 1); }
  public ByteBuffer hyperlinkInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 24, 1); }
  public String followedHyperlink() { int o = __offset(26); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer followedHyperlinkAsByteBuffer() { return __vector_as_bytebuffer(26, 1); }
  public ByteBuffer followedHyperlinkInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 26, 1); }

  public static int createThemePalletModel(FlatBufferBuilder builder,
      int accent1Offset,
      int accent2Offset,
      int accent3Offset,
      int accent4Offset,
      int accent5Offset,
      int accent6Offset,
      int dark1Offset,
      int dark2Offset,
      int light1Offset,
      int light2Offset,
      int hyperlinkOffset,
      int followedHyperlinkOffset) {
    builder.startTable(12);
    ThemePalletModel.addFollowedHyperlink(builder, followedHyperlinkOffset);
    ThemePalletModel.addHyperlink(builder, hyperlinkOffset);
    ThemePalletModel.addLight2(builder, light2Offset);
    ThemePalletModel.addLight1(builder, light1Offset);
    ThemePalletModel.addDark2(builder, dark2Offset);
    ThemePalletModel.addDark1(builder, dark1Offset);
    ThemePalletModel.addAccent6(builder, accent6Offset);
    ThemePalletModel.addAccent5(builder, accent5Offset);
    ThemePalletModel.addAccent4(builder, accent4Offset);
    ThemePalletModel.addAccent3(builder, accent3Offset);
    ThemePalletModel.addAccent2(builder, accent2Offset);
    ThemePalletModel.addAccent1(builder, accent1Offset);
    return ThemePalletModel.endThemePalletModel(builder);
  }

  public static void startThemePalletModel(FlatBufferBuilder builder) { builder.startTable(12); }
  public static void addAccent1(FlatBufferBuilder builder, int accent1Offset) { builder.addOffset(0, accent1Offset, 0); }
  public static void addAccent2(FlatBufferBuilder builder, int accent2Offset) { builder.addOffset(1, accent2Offset, 0); }
  public static void addAccent3(FlatBufferBuilder builder, int accent3Offset) { builder.addOffset(2, accent3Offset, 0); }
  public static void addAccent4(FlatBufferBuilder builder, int accent4Offset) { builder.addOffset(3, accent4Offset, 0); }
  public static void addAccent5(FlatBufferBuilder builder, int accent5Offset) { builder.addOffset(4, accent5Offset, 0); }
  public static void addAccent6(FlatBufferBuilder builder, int accent6Offset) { builder.addOffset(5, accent6Offset, 0); }
  public static void addDark1(FlatBufferBuilder builder, int dark1Offset) { builder.addOffset(6, dark1Offset, 0); }
  public static void addDark2(FlatBufferBuilder builder, int dark2Offset) { builder.addOffset(7, dark2Offset, 0); }
  public static void addLight1(FlatBufferBuilder builder, int light1Offset) { builder.addOffset(8, light1Offset, 0); }
  public static void addLight2(FlatBufferBuilder builder, int light2Offset) { builder.addOffset(9, light2Offset, 0); }
  public static void addHyperlink(FlatBufferBuilder builder, int hyperlinkOffset) { builder.addOffset(10, hyperlinkOffset, 0); }
  public static void addFollowedHyperlink(FlatBufferBuilder builder, int followedHyperlinkOffset) { builder.addOffset(11, followedHyperlinkOffset, 0); }
  public static int endThemePalletModel(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishThemePalletModelBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedThemePalletModelBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ThemePalletModel get(int j) { return get(new ThemePalletModel(), j); }
    public ThemePalletModel get(ThemePalletModel obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

