// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package global

import "strconv"

type Global_image_type int8

const (
	Global_image_typejpeg Global_image_type = 0
	Global_image_typepng  Global_image_type = 1
	Global_image_typegif  Global_image_type = 2
	Global_image_typebmp  Global_image_type = 3
	Global_image_typetiff Global_image_type = 4
)

var EnumNamesGlobal_image_type = map[Global_image_type]string{
	Global_image_typejpeg: "jpeg",
	Global_image_typepng:  "png",
	Global_image_typegif:  "gif",
	Global_image_typebmp:  "bmp",
	Global_image_typetiff: "tiff",
}

var EnumValuesGlobal_image_type = map[string]Global_image_type{
	"jpeg": Global_image_typejpeg,
	"png":  Global_image_typepng,
	"gif":  Global_image_typegif,
	"bmp":  Global_image_typebmp,
	"tiff": Global_image_typetiff,
}

func (v Global_image_type) String() string {
	if s, ok := EnumNamesGlobal_image_type[v]; ok {
		return s
	}
	return "Global_image_type(" + strconv.FormatInt(int64(v), 10) + ")"
}
