// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package global

import "strconv"

type global_image_type int8

const (
	global_image_typejpeg global_image_type = 0
	global_image_typepng  global_image_type = 1
	global_image_typegif  global_image_type = 2
	global_image_typebmp  global_image_type = 3
	global_image_typetiff global_image_type = 4
)

var EnumNamesglobal_image_type = map[global_image_type]string{
	global_image_typejpeg: "jpeg",
	global_image_typepng:  "png",
	global_image_typegif:  "gif",
	global_image_typebmp:  "bmp",
	global_image_typetiff: "tiff",
}

var EnumValuesglobal_image_type = map[string]global_image_type{
	"jpeg": global_image_typejpeg,
	"png":  global_image_typepng,
	"gif":  global_image_typegif,
	"bmp":  global_image_typebmp,
	"tiff": global_image_typetiff,
}

func (v global_image_type) String() string {
	if s, ok := EnumNamesglobal_image_type[v]; ok {
		return s
	}
	return "global_image_type(" + strconv.FormatInt(int64(v), 10) + ")"
}
