// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package global

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type global_picture_settings struct {
	_tab flatbuffers.Table
}

func GetRootAsglobal_picture_settings(buf []byte, offset flatbuffers.UOffsetT) *global_picture_settings {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &global_picture_settings{}
	x.Init(buf, n+offset)
	return x
}

func Finishglobal_picture_settingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsglobal_picture_settings(buf []byte, offset flatbuffers.UOffsetT) *global_picture_settings {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &global_picture_settings{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedglobal_picture_settingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *global_picture_settings) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *global_picture_settings) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *global_picture_settings) ImageType() global_image_type {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return global_image_type(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *global_picture_settings) MutateImageType(n global_image_type) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func global_picture_settingsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func global_picture_settingsAddImageType(builder *flatbuffers.Builder, imageType global_image_type) {
	builder.PrependInt8Slot(0, int8(imageType), 0)
}
func global_picture_settingsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
