from cffi import FFI

ffi = FFI()

# Load the C header file generated by cbindgen
with open("lib/methods.h") as f:
    ffi.cdef(f.read())

# Specify the shared library file
ffi.set_source(
    "draviavemal_openxml_office_ffi",
    """
    #include "bindings.h"
    """,
    libraries=["draviavemal_openxml_office_ffi"],  # Name of your Rust library
    library_dirs=["./lib"],  # Path to the shared library
    include_dirs=["./lib"]
)

if __name__ == "__main__":
    ffi.compile()
