namespace openxml_office_fbs.spreadsheet;

// Common worksheet properties - Start

enum worksheet_cell_data_type: byte{
    auto=0,
    number=1,
    boolean=2,
    string=3,
    shared_string=4,
    inline_string=5,
    error=6,
}

table worksheet_column_properties{
    min: uint32;
    max: uint32;
    width: float = null;
    hidden: bool = null;
    best_fit: bool = null;
    style_id_ptr: uint64 = null;
}

table worksheet_cell_property{
    value: string;
    formula: string;
    data_type: worksheet_cell_data_type;
    style_id_ptr: uint64 = null;
}

// Common worksheet properties - End

// worksheet_set_column_ref_properties - Start

table worksheet_set_column_ref_properties{
    worksheet_ptr: uint64;
    cell_ref: string;
    column_properties: worksheet_column_properties;
}

// worksheet_set_column_ref_properties - End

// worksheet_set_column_index_properties - Start

table worksheet_set_column_index_properties{
    worksheet_ptr: uint64;
    column_index: uint16;
    column_properties: worksheet_column_properties;
}

// worksheet_set_column_index_properties - End

// worksheet_set_row_ref_properties - Start

table worksheet_set_row_index_properties{
    worksheet_ptr: uint64;
    row_index: uint32;
    row_properties: worksheet_row_properties(required);
}

table worksheet_row_properties{
    height: float = null;
    hidden: bool = null;
    thick_top: bool = null;
    thick_bottom: bool = null;
    style_id_ptr: uint64 = null;
}
// worksheet_set_row_ref_properties - End

// Worksheet set cell ref value - Start

table worksheet_set_cell_ref_value{
    worksheet_ptr: uint64;
    cell_ref: string;
    column_cells: [worksheet_cell_property](required);
}

// Worksheet set cell ref value - End

// Worksheet set cell index value - Start

table worksheet_set_cell_index_value{
    worksheet_ptr: uint64;
    row_index: uint32;
    column_index: uint16;
    column_cells: [worksheet_cell_property](required);
}

// Worksheet set cell index value - End

// Worksheet flush - Start

table worksheet_flush{
    worksheet_ptr: uint64;
}

// Worksheet flush - End

// Common reference range - Start

table worksheet_reference_range {
    column_start: uint16;
    column_end: uint16;
    row_start: uint32;
    row_end: uint32;
}

// Common reference range - End

// worksheet_set_merge_cell - Start

table worksheet_set_merge_cell {
    worksheet_ptr: uint64;
    ref_range: worksheet_reference_range(required);
}

// worksheet_set_merge_cell - End

// worksheet_remove_merge_cell - Start

table worksheet_remove_merge_cell {
    worksheet_ptr: uint64;
    ref_range: worksheet_reference_range(required);
}

// worksheet_remove_merge_cell - End

// worksheet_set_hyperlink - Start

table worksheet_set_hyperlink {
    worksheet_ptr: uint64;
    display: string;
    link: string;
    ref_range: worksheet_reference_range(required);
}

// worksheet_set_hyperlink - End

// worksheet_remove_hyperlink - Start

table worksheet_remove_hyperlink {
    worksheet_ptr: uint64;
    ref_range: worksheet_reference_range(required);
}

// worksheet_remove_hyperlink - End

// worksheet_delete_sheet - Start

table worksheet_delete_sheet {
    worksheet_ptr: uint64;
}

// worksheet_delete_sheet - End

// worksheet_get_range_cell_properties - Start

table worksheet_get_range_cell_properties {
    worksheet_ptr: uint64;
    ref_range: worksheet_reference_range(required);
}

table worksheet_cell_package {
    cell_ref: string;
    row_index: uint32;
    column_index: uint16;
    cell_property: worksheet_cell_property;
}

table worksheet_get_range_cell_properties_return {
    cell_packages: [worksheet_cell_package];
}

// worksheet_get_range_cell_properties - End

// worksheet_list_merge_cell - Start

table worksheet_list_merge_cell {
    worksheet_ptr: uint64;
}

table worksheet_list_merge_cell_return {
    ranges: [worksheet_reference_range];
}

// worksheet_list_merge_cell - End

// worksheet_list_hyperlinks - Start

table worksheet_list_hyperlinks {
    worksheet_ptr: uint64;
}

table worksheet_hyperlink {
    display: string;
    link: string;
    ref_range: worksheet_reference_range;
}

table worksheet_list_hyperlinks_return {
    hyperlinks: [worksheet_hyperlink];
}

// worksheet_list_hyperlinks - End

// worksheet_add_picture - Start

enum worksheet_image_type: byte {
    jpeg = 0,
    png = 1,
    gif = 2,
    bmp = 3,
    tiff = 4,
}

table worksheet_anchor_position {
    column: uint16;
    column_offset: uint64;
    row: uint32;
    row_offset: uint64;
}

enum worksheet_excel_hyperlink_type: byte {
    existing_file = 0,
    web_url = 1,
    target_sheet = 2,
}

table worksheet_excel_hyperlink {
    display: string;
    link_type: worksheet_excel_hyperlink_type;
    link: string;
}

table worksheet_picture_setting {
    image_type: worksheet_image_type;
    from: worksheet_anchor_position(required);
    to: worksheet_anchor_position(required);
    hyperlink: worksheet_excel_hyperlink;
}

table worksheet_add_picture {
    worksheet_ptr: uint64;
    image_path: string;
    picture_setting: worksheet_picture_setting(required);
}

// worksheet_add_picture - End
