// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type excel_create struct {
	_tab flatbuffers.Table
}

func GetRootAsexcel_create(buf []byte, offset flatbuffers.UOffsetT) *excel_create {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &excel_create{}
	x.Init(buf, n+offset)
	return x
}

func Finishexcel_createBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsexcel_create(buf []byte, offset flatbuffers.UOffsetT) *excel_create {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &excel_create{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedexcel_createBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *excel_create) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *excel_create) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *excel_create) FileName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *excel_create) ExcelSettings(obj *excel_settings) *excel_settings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(excel_settings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func excel_createStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func excel_createAddFileName(builder *flatbuffers.Builder, fileName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(fileName), 0)
}
func excel_createAddExcelSettings(builder *flatbuffers.Builder, excelSettings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(excelSettings), 0)
}
func excel_createEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
