// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type worksheet_set_column_index_properties struct {
	_tab flatbuffers.Table
}

func GetRootAsworksheet_set_column_index_properties(buf []byte, offset flatbuffers.UOffsetT) *worksheet_set_column_index_properties {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &worksheet_set_column_index_properties{}
	x.Init(buf, n+offset)
	return x
}

func Finishworksheet_set_column_index_propertiesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsworksheet_set_column_index_properties(buf []byte, offset flatbuffers.UOffsetT) *worksheet_set_column_index_properties {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &worksheet_set_column_index_properties{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedworksheet_set_column_index_propertiesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *worksheet_set_column_index_properties) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *worksheet_set_column_index_properties) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *worksheet_set_column_index_properties) WorksheetPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *worksheet_set_column_index_properties) MutateWorksheetPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *worksheet_set_column_index_properties) CellIndex() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *worksheet_set_column_index_properties) MutateCellIndex(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func (rcv *worksheet_set_column_index_properties) ColumnProperties(obj *worksheet_column_properties) *worksheet_column_properties {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(worksheet_column_properties)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func worksheet_set_column_index_propertiesStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func worksheet_set_column_index_propertiesAddWorksheetPtr(builder *flatbuffers.Builder, worksheetPtr uint64) {
	builder.PrependUint64Slot(0, worksheetPtr, 0)
}
func worksheet_set_column_index_propertiesAddCellIndex(builder *flatbuffers.Builder, cellIndex uint16) {
	builder.PrependUint16Slot(1, cellIndex, 0)
}
func worksheet_set_column_index_propertiesAddColumnProperties(builder *flatbuffers.Builder, columnProperties flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(columnProperties), 0)
}
func worksheet_set_column_index_propertiesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
