// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type worksheet_cell_properties struct {
	_tab flatbuffers.Table
}

func GetRootAsworksheet_cell_properties(buf []byte, offset flatbuffers.UOffsetT) *worksheet_cell_properties {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &worksheet_cell_properties{}
	x.Init(buf, n+offset)
	return x
}

func Finishworksheet_cell_propertiesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsworksheet_cell_properties(buf []byte, offset flatbuffers.UOffsetT) *worksheet_cell_properties {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &worksheet_cell_properties{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedworksheet_cell_propertiesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *worksheet_cell_properties) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *worksheet_cell_properties) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *worksheet_cell_properties) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *worksheet_cell_properties) Formula() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *worksheet_cell_properties) DataType() worksheet_cell_data_type {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return worksheet_cell_data_type(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *worksheet_cell_properties) MutateDataType(n worksheet_cell_data_type) bool {
	return rcv._tab.MutateInt8Slot(8, int8(n))
}

func (rcv *worksheet_cell_properties) StyleIdPtr() *uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		v := rcv._tab.GetUint64(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *worksheet_cell_properties) MutateStyleIdPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func worksheet_cell_propertiesStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func worksheet_cell_propertiesAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(value), 0)
}
func worksheet_cell_propertiesAddFormula(builder *flatbuffers.Builder, formula flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(formula), 0)
}
func worksheet_cell_propertiesAddDataType(builder *flatbuffers.Builder, dataType worksheet_cell_data_type) {
	builder.PrependInt8Slot(2, int8(dataType), 0)
}
func worksheet_cell_propertiesAddStyleIdPtr(builder *flatbuffers.Builder, styleIdPtr uint64) {
	builder.PrependUint64(styleIdPtr)
	builder.Slot(3)
}
func worksheet_cell_propertiesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
