// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package presentation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type power_point_create struct {
	_tab flatbuffers.Table
}

func GetRootAspower_point_create(buf []byte, offset flatbuffers.UOffsetT) *power_point_create {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &power_point_create{}
	x.Init(buf, n+offset)
	return x
}

func Finishpower_point_createBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAspower_point_create(buf []byte, offset flatbuffers.UOffsetT) *power_point_create {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &power_point_create{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedpower_point_createBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *power_point_create) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *power_point_create) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *power_point_create) FileName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *power_point_create) PowerPointSettings(obj *power_point_settings) *power_point_settings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(power_point_settings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func power_point_createStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func power_point_createAddFileName(builder *flatbuffers.Builder, fileName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(fileName), 0)
}
func power_point_createAddPowerPointSettings(builder *flatbuffers.Builder, powerPointSettings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(powerPointSettings), 0)
}
func power_point_createEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
