// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package presentation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type power_point_create_return struct {
	_tab flatbuffers.Table
}

func GetRootAspower_point_create_return(buf []byte, offset flatbuffers.UOffsetT) *power_point_create_return {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &power_point_create_return{}
	x.Init(buf, n+offset)
	return x
}

func Finishpower_point_create_returnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAspower_point_create_return(buf []byte, offset flatbuffers.UOffsetT) *power_point_create_return {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &power_point_create_return{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedpower_point_create_returnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *power_point_create_return) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *power_point_create_return) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *power_point_create_return) PowerPointPtr() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *power_point_create_return) MutatePowerPointPtr(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func power_point_create_returnStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func power_point_create_returnAddPowerPointPtr(builder *flatbuffers.Builder, powerPointPtr uint64) {
	builder.PrependUint64Slot(0, powerPointPtr, 0)
}
func power_point_create_returnEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
