// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet_2007

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ExcelSettingsModel struct {
	_tab flatbuffers.Table
}

func GetRootAsExcelSettingsModel(buf []byte, offset flatbuffers.UOffsetT) *ExcelSettingsModel {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ExcelSettingsModel{}
	x.Init(buf, n+offset)
	return x
}

func FinishExcelSettingsModelBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsExcelSettingsModel(buf []byte, offset flatbuffers.UOffsetT) *ExcelSettingsModel {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ExcelSettingsModel{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedExcelSettingsModelBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ExcelSettingsModel) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ExcelSettingsModel) Table() flatbuffers.Table {
	return rcv._tab
}

func ExcelSettingsModelStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ExcelSettingsModelEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
