// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package spreadsheet_2007

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ExcelPropertiesModel struct {
	_tab flatbuffers.Table
}

func GetRootAsExcelPropertiesModel(buf []byte, offset flatbuffers.UOffsetT) *ExcelPropertiesModel {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ExcelPropertiesModel{}
	x.Init(buf, n+offset)
	return x
}

func FinishExcelPropertiesModelBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsExcelPropertiesModel(buf []byte, offset flatbuffers.UOffsetT) *ExcelPropertiesModel {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ExcelPropertiesModel{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedExcelPropertiesModelBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ExcelPropertiesModel) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ExcelPropertiesModel) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ExcelPropertiesModel) IsInMemory() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ExcelPropertiesModel) MutateIsInMemory(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func ExcelPropertiesModelStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ExcelPropertiesModelAddIsInMemory(builder *flatbuffers.Builder, isInMemory bool) {
	builder.PrependBoolSlot(0, isInMemory, false)
}
func ExcelPropertiesModelEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
