// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document_2007

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DocumentPropertiesModel struct {
	_tab flatbuffers.Table
}

func GetRootAsDocumentPropertiesModel(buf []byte, offset flatbuffers.UOffsetT) *DocumentPropertiesModel {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DocumentPropertiesModel{}
	x.Init(buf, n+offset)
	return x
}

func FinishDocumentPropertiesModelBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDocumentPropertiesModel(buf []byte, offset flatbuffers.UOffsetT) *DocumentPropertiesModel {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DocumentPropertiesModel{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDocumentPropertiesModelBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DocumentPropertiesModel) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DocumentPropertiesModel) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DocumentPropertiesModel) IsInMemory() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DocumentPropertiesModel) MutateIsInMemory(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func DocumentPropertiesModelStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DocumentPropertiesModelAddIsInMemory(builder *flatbuffers.Builder, isInMemory bool) {
	builder.PrependBoolSlot(0, isInMemory, false)
}
func DocumentPropertiesModelEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
