// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package document_2007

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DocumentSettingsModel struct {
	_tab flatbuffers.Table
}

func GetRootAsDocumentSettingsModel(buf []byte, offset flatbuffers.UOffsetT) *DocumentSettingsModel {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DocumentSettingsModel{}
	x.Init(buf, n+offset)
	return x
}

func FinishDocumentSettingsModelBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDocumentSettingsModel(buf []byte, offset flatbuffers.UOffsetT) *DocumentSettingsModel {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DocumentSettingsModel{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDocumentSettingsModelBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DocumentSettingsModel) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DocumentSettingsModel) Table() flatbuffers.Table {
	return rcv._tab
}

func DocumentSettingsModelStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func DocumentSettingsModelEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
