name: C# Doc Build And Publish

permissions:
  contents: read
  pages: write
  id-token: write

on:
  workflow_run:
    workflows: [".NET 7 Build and Publish to NuGet"]
    types:
      - completed

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen
      - name: Build Docs
        run: doxygen Doxyfile.conf
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./docs"
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
