name: Package Build and Publish to NuGet
permissions:
  contents: write
  pages: write
  id-token: write
on:
  push:
    branches:
      - main
    paths:
      - 'Directory.Build.props'
jobs:
  build-CsProj:
    runs-on: windows-latest
    environment: Build
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Test Runner
        working-directory: Tests
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=../TestResults/coverage.xml --no-build --verbosity quiet
      - name: Publish Coverage
        working-directory: TestResults
        run: curl -Ls https://coverage.codacy.com/get.sh | bash
      - name: Pack Project DLL
        run: dotnet pack -c Release -o nupkgs
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nupkgs
          path: nupkgs/*
  publish-nuget:
    needs: build-CsProj
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: nupkgs
          path: nupkgs
      - name: Publish to NuGet
        run: dotnet nuget push "nupkgs/*" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
