name: Alpha Package Build and Publish to NuGet
permissions:
  contents: write
  pages: write
  id-token: write
on:
  push:
    branches:
      - alpha
jobs:
  build-CsProj:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Install xmlstarlet
        run: sudo apt-get install -y xmlstarlet
      - name: Pack Project DLL
        run: |
          git fetch --tags
          BASE_VERSION=$(xmlstarlet sel -t -v "/Project/PropertyGroup/Version" Directory.Build.props)
          LATEST_TAG=$(git tag -l "${BASE_VERSION}-Alpha.*" | sort -V | tail -n 1)
          if [ -z "$LATEST_TAG" ]; then
              PACKAGE_VERSION="${BASE_VERSION}-Alpha.1"
          else
              CURRENT_ALPHA=$(echo "$LATEST_TAG" | sed -E 's/.*Alpha\.([0-9]+)$/\1/')
              NEXT_ALPHA=$((CURRENT_ALPHA + 1))
              PACKAGE_VERSION="${BASE_VERSION}-Alpha.${NEXT_ALPHA}"
          fi
          dotnet pack -c Release -o nupkgs -p:Version=${PACKAGE_VERSION}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nupkgs
          path: nupkgs/*
  publish-nuget:
    needs: build-CsProj
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: nupkgs
          path: nupkgs
      - name: Publish to NuGet
        run: dotnet nuget push "nupkgs/*" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
  tag-version:
    needs: publish-nuget
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install xmlstarlet
        run: sudo apt-get install -y xmlstarlet
      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --tags
          BASE_VERSION=$(xmlstarlet sel -t -v "/Project/PropertyGroup/Version" Directory.Build.props)
          echo $BASE_VERSION
          LATEST_TAG=$(git tag -l "${BASE_VERSION}-Alpha.*" | sort -V | tail -n 1)
          echo $LATEST_TAG
          if [ -z "$LATEST_TAG" ]; then
              PACKAGE_VERSION="${BASE_VERSION}-Alpha.1"
              echo "vemal"
          else
              CURRENT_ALPHA=$(echo "$LATEST_TAG" | sed -E 's/.*Alpha\.([0-9]+)$/\1/')
              NEXT_ALPHA=$((CURRENT_ALPHA + 1))
              PACKAGE_VERSION="${BASE_VERSION}-Alpha.${NEXT_ALPHA}"
              echo "Dravia"
              echo $PACKAGE_VERSION
          fi
          git tag "v${PACKAGE_VERSION}"
          git push --tags