name: Stable Release Pipeline

on:
  push:
    branches:
      - stable
    paths:
      - "Directory.Build.props"
jobs:
  build-CsProj:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: "7.0"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Pack Project DLL
        run: dotnet pack -c Release -o nupkgs
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.4.0
        with:
          name: nupkgs
          path: nupkgs/*
  publish-nuget:
    needs: build-CsProj
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
      - name: Download Artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: nupkgs
          path: nupkgs
      - name: Publish to NuGet
        run: dotnet nuget push "nupkgs/*" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
  tag-version:
    needs: publish-nuget
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
      - name: Install xmlstarlet
        run: sudo apt-get install -y xmlstarlet
      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(xmlstarlet sel -t -v "/Project/PropertyGroup/Version" Directory.Build.props)
          git tag "v${VERSION}"
          git push --tags