name: .NET 7 Build and Publish to NuGet

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0"
      - name: Install Doxygen
        run: sudo apt-get install doxygen
      - name: Build Docs
        run: doxygen Doxyfile.conf
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./docs"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      - name: Restore dependencies
        run: dotnet restore
      - name: Bump Minor Version
        run: |
          dotnet tool install --global dotnet-bump
          dotnet bump minor -p [./Excel/Excel.csproj]
          dotnet bump minor -p [./Document/Document.csproj]
          dotnet bump minor -p [./Presentation/Presentation.csproj]
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'contact@draviavemal.com'
          git commit -am "Bump minor version"
          git push
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Pack Excel Project
        run: dotnet pack ./Excel/Excel.csproj --no-build -c Release -o nupkgs
      - name: Pack Document Project
        run: dotnet pack ./Document/Document.csproj --no-build -c Release -o nupkgs
      - name: Pack Presentation Project
        run: dotnet pack ./Presentation/Presentation.csproj --no-build -c Release -o nupkgs
      - name: Extract Version from Directory.Build.props
        id: get_version
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" Directory.Build.props)
          echo "Version: $VERSION"
          echo "::set-output name=version::$VERSION"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nupkgs
          path: nupkgs/*.nupkg

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: nupkgs
          path: nupkgs
      - name: Publish to NuGet
        run: dotnet nuget push "nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          tag_name: ${{ needs.build.outputs.version }}
          release_name: Release ${{ needs.build.outputs.version }}
          draft: false
          prerelease: false
          body: "Auto Release By Actions"
