name: .NET 7 Build and Publish to NuGet

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'  # Use .NET 7

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Pack Excel Project
      run: dotnet pack ./Excel/Excel.csproj --no-build -c Release -o nupkgs
    
    - name: Pack Word Project
      run: dotnet pack ./Word/Word.csproj --no-build -c Release -o nupkgs
    
    - name: Pack Presentation Project
      run: dotnet pack ./Presentation/Presentation.csproj --no-build -c Release -o nupkgs
    
    - name: Publish to NuGet
      run: dotnet nuget push "nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
    
