name: Build Validation and Coverage Test

on:
  pull_request:
    branches:
      - stable
      - alpha
jobs:
  pr-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: "7.0"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Pack Project DLL
        run: dotnet pack -c Release -o nupkgs
  pr-coverage:
    needs: pr-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: "7.0"
      - name: Test Runner
        working-directory: Tests
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=../TestResults/cobertura.xml
