name: .NET 7 Build on PR
permissions:
  contents: write
  pages: write
  id-token: write
on:
  pull_request:
    branches:
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0"
      - name: Test Runner
        working-directory: Tests
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=../TestResults/cobertura.xml
      - name: Publish Coverage
        working-directory: TestResults
        run: export CODACY_PROJECT_TOKEN=${{secrets.CODACY_PROJECT_TOKEN}} && bash <(curl -Ls https://coverage.codacy.com/get.sh)
  build:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Pack Project DLL
        run: dotnet pack -c Release -o nupkgs
