name: .NET 7 Build on PR
permissions:
  contents: write
  pages: write
  id-token: write
on:
  pull_request:
    branches:
      - main
jobs:
  coverage:
    runs-on: windows-latest
    environment: Build
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0"
      - name: Test Runner
        working-directory: Tests
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=../TestResults/coverage.xml --verbosity quiet
      - name: Publish Coverage
        working-directory: TestResults
        run: export CODACY_PROJECT_TOKEN=${{env.CODACY_PROJECT_TOKEN}} && curl -Ls https://coverage.codacy.com/get.sh | bash
  build:
    needs: coverage
    runs-on: windows-latest
    environment: Build
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Pack Project DLL
        run: dotnet pack -c Release -o nupkgs
